### ISSUE TITLE
require('core.mappings') adds 265 ms to startup time

### ISSUE THREAD

**Issue by jay-babu** [AstroNvim/AstroNvim#1579] opened 2023-02-18 18:49 UTC
### Checklist

- [ ] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

nightly (v2.11.8-168-g471c0e4)

### Neovim version (>= 0.8)

0.9

### Operating system/version

WSL running Arch

### Describe the bug

The below snippet (parts of it) adds about 260 ms in latency to the startup of latency. In particular I don't have `gdu` and `btm` installed. Commenting out those lines brings the startup latency back down to `20ms`. My guess is `vim.fn.executable` is slow when an executable is not installed for some reason.

```lua
-- Terminal
if is_available "toggleterm.nvim" then
  maps.n["<leader>t"] = sections.t
  local toggle_term_cmd = require("core.utils").toggle_term_cmd
  if vim.fn.executable "lazygit" == 1 then
    maps.n["<leader>g"] = sections.g
    maps.n["<leader>gg"] = { function() toggle_term_cmd "lazygit" end, desc = "ToggleTerm lazygit" }
    maps.n["<leader>tl"] = { function() toggle_term_cmd "lazygit" end, desc = "ToggleTerm lazygit" }
  end
  if vim.fn.executable "node" == 1 then
    maps.n["<leader>tn"] = { function() toggle_term_cmd "node" end, desc = "ToggleTerm node" }
  end
  if vim.fn.executable "gdu" == 1 then
    maps.n["<leader>tu"] = { function() toggle_term_cmd "gdu" end, desc = "ToggleTerm gdu" }
  end
  if vim.fn.executable "btm" == 1 then
    maps.n["<leader>tt"] = { function() toggle_term_cmd "btm" end, desc = "ToggleTerm btm" }
  end
  local python = vim.fn.executable "python" == 1 and "python" or vim.fn.executable "python3" == 1 and "python3"
  if python then maps.n["<leader>tp"] = { function() toggle_term_cmd(python) end, desc = "ToggleTerm python" } end
  maps.n["<leader>tf"] = { "<cmd>ToggleTerm direction=float<cr>", desc = "ToggleTerm float" }
  maps.n["<leader>th"] = { "<cmd>ToggleTerm size=10 direction=horizontal<cr>", desc = "ToggleTerm horizontal split" }
  maps.n["<leader>tv"] = { "<cmd>ToggleTerm size=80 direction=vertical<cr>", desc = "ToggleTerm vertical split" }
  maps.n["<F7>"] = { "<cmd>ToggleTerm<cr>", desc = "Toggle terminal" }
  maps.t["<F7>"] = maps.n["<F7>"]
  maps.n["<C-'>"] = maps.n["<F7>"]
  maps.t["<C-'>"] = maps.n["<F7>"]
end
```

### Steps to Reproduce

1. Don't have `gdu` installed
2. Comment out
```lua
  if vim.fn.executable "gdu" == 1 then
    maps.n["<leader>tu"] = { function() toggle_term_cmd "gdu" end, desc = "ToggleTerm gdu" }
  end
```
3. `hyperfine 'nvim +q' --warmup 8 -i` should be arount 20ms
4. Uncomment it
5. `hyperfine 'nvim +q' --warmup 8 -i` should be around 300ms

### Expected behavior

Latency is around 20ms

### Additional Context

```
❯ echo $PATH
/home/archy/.local/share/gem/ruby/3.0.0/bin /home/archy/go/bin /home/archy/.cargo/bin /home/archy/.local/bin /home/archy/.luarocks /home/archy/.local/share/gem/ruby/3.0.0/bin /home/archy/go/bin /home/archy/.cargo/bin /home/archy/.local/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /usr/lib/wsl/lib /mnt/c/Program Files/PowerShell/7 /mnt/c/Program Files/Microsoft/jdk-11.0.18.10-hotspot/bin /mnt/c/Program Files/Alacritty/ /mnt/c/Program Files/Oculus/Support/oculus-runtime /mnt/c/Program Files (x86)/Razer Chroma SDK/bin /mnt/c/Program Files/Razer Chroma SDK/bin /mnt/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler /mnt/c/Program Files (x86)/Razer/ChromaBroadcast/bin /mnt/c/Program Files/Razer/ChromaBroadcast/bin /mnt/c/Windows/system32 /mnt/c/Windows /mnt/c/Windows/System32/Wbem /mnt/c/Windows/System32/WindowsPowerShell/v1.0/ /mnt/c/Windows/System32/OpenSSH/ /mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common /mnt/c/ProgramData/chocolatey/bin /mnt/c/Users/jay/miniconda3 /mnt/c/Users/jay/miniconda3/Library/mingw-w64/bin /mnt/c/Users/jay/miniconda3/Library/usr/bin /mnt/c/Users/jay/miniconda3/Library/bin /mnt/c/Users/jay/miniconda3/Scripts /mnt/c/Users/jay/AppData/Local/Microsoft/WindowsApps /mnt/c/Users/jay/AppData/Roaming/npm /mnt/c/Program Files/heroku/bin /mnt/c/Program Files/dotnet/ /mnt/c/Program Files (x86)/GitHub CLI/ /mnt/c/WINDOWS/system32 /mnt/c/WINDOWS /mnt/c/WINDOWS/System32/Wbem /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/ /mnt/c/WINDOWS/System32/OpenSSH/ /mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR /mnt/c/Program Files/Go/bin /mnt/c/Program Files (x86)/gsudo/ /mnt/c/Program Files/Docker/Docker/resources/bin /mnt/c/Program Files/Git/cmd /mnt/c/Program Files/nodejs/ /mnt/c/Program Files/GitHub CLI/ /mnt/c/Program Files/PowerShell/7/ /mnt/c/Users/jay/AppData/Local/Programs/Python/Python310/Scripts/ /mnt/c/Users/jay/AppData/Local/Programs/Python/Python310/ /mnt/c/Users/jay/AppData/Local/Microsoft/WindowsApps /mnt/c/Program Files/heroku/bin /mnt/c/Users/jay/AppData/Local/Programs/oh-my-posh/bin /mnt/c/Users/jay/AppData/Local/Programs/oh-my-posh/themes /mnt/c/Users/jay/AppData/Local/Android/Sdk/cmdline-tools/latest/bin /mnt/c/Users/jay/AppData/Local/Android/Sdk/tools/bin /mnt/c/Users/jay/AppData/Local/Android/Sdk/platform-tools /mnt/c/Users/jay/AppData/Local/Android/Sdk/emulator /mnt/c/Users/jay/go /mnt/c/Users/jay/Documents/bin /mnt/c/Users/jay/go/bin /mnt/c/Users/jay/AppData/Local/Programs/Microsoft VS Code/bin /mnt/c/Users/jay/AppData/Local/JetBrains/Toolbox/scripts /mnt/c/Users/jay/go/bin /mnt/c/Users/jay/AppData/Roaming/npm /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl
```

**Comment by mehalter** [comment] 2023-02-18 21:00
This shouldn't be an issue. It sounds like from the discord this is due to the `fish` shell and was resolved by adding `vim.opt.shell = vim.fn.exepath("bash")` to the configuration.

**Closed by mehalter** 2023-02-18 21:00 UTC
Labels: bug

**Comment by jay-babu** [comment] 2023-02-18 21:31
A little confused on why this shouldn't be an issue? @mehalter 

This fixed a separate issue, `vim.opt.shell = vim.fn.exepath("bash")`. Namely, the slowness of `vim-tpipeline` starting up

**Comment by mehalter** [comment] 2023-02-18 21:32
Ah I see, I misunderstood your comment on the discord! Ill take a look next week and report back on the v3 PR!

**Comment by luxus** [comment] 2023-02-18 21:34
i guess this issue is related to wsl, I cannot reproduce it on mac

**Comment by jay-babu** [comment] 2023-02-21 23:52
@mehalter, in case this slipped since the issue is closed

PS, surprisingly my WSL setup is faster at starting up than my mac's

**Comment by mehalter** [comment] 2023-02-21 23:55
No worries, I'm still planning on taking a look!

**Comment by Uzaaft** [comment] 2023-03-01 16:27
@jay-babu  A couple of things while we're looking into the issue.

1. Have you by any chance edited your config files in Windows?
2. Are you running astronvim inside the `/mnt/` folder?

**Comment by Uzaaft** [comment] 2023-03-01 16:32
Also. Could you benchmark your terminal when you run `btm` in hyperfine? I think the issue might be because of the usage of `mnt` in your path env

**Comment by jay-babu** [comment] 2023-03-03 01:36
> @jay-babu  A couple of things while we're looking into the issue.
> 
> 
> 
> 1. Have you by any chance edited your config files in Windows? Nope
> 
> 2. Are you running astronvim inside the `/mnt/` folder? Nope

**Comment by jay-babu** [comment] 2023-03-03 03:58
I think this is a problem with my system. The path is probably too big. I'll look into making it smaller

```
❯ time which ssss
which: no ssss in (/home/archy/.local/share/gem/ruby/3.0.0/bin:/home/archy/go/bin:/home/archy/.cargo/bin:/home/archy/.local/bin:/home/archy/.luarocks:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/PowerShell/7:/mnt/c/Program Files/Microsoft/jdk-11.0.18.10-hotspot/bin:/mnt/c/Program Files/Alacritty/:/mnt/c/Program Files/Oculus/Support/oculus-runtime:/mnt/c/Program Files (x86)/Razer Chroma SDK/bin:/mnt/c/Program Files/Razer Chroma SDK/bin:/mnt/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler:/mnt/c/Program Files (x86)/Razer/ChromaBroadcast/bin:/mnt/c/Program Files/Razer/ChromaBroadcast/bin:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Users/jay/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/jay/AppData/Roaming/npm:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files (x86)/GitHub CLI/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files/Go/bin:/mnt/c/Program Files (x86)/gsudo/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/nodejs/:/mnt/c/Program Files/GitHub CLI/:/mnt/c/Program Files/PowerShell/7/:/mnt/c/Users/jay/AppData/Local/Programs/Python/Python310/Scripts/:/mnt/c/Users/jay/AppData/Local/Programs/Python/Python310/:/mnt/c/Users/jay/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/jay/AppData/Local/Programs/oh-my-posh/bin:/mnt/c/Users/jay/AppData/Local/Programs/oh-my-posh/themes:/mnt/c/Users/jay/AppData/Local/Android/Sdk/cmdline-tools/latest/bin:/mnt/c/Users/jay/AppData/Local/Android/Sdk/tools/bin:/mnt/c/Users/jay/AppData/Local/Android/Sdk/platform-tools:/mnt/c/Users/jay/AppData/Local/Android/Sdk/emulator:/mnt/c/Users/jay/Documents/bin:/mnt/c/Users/jay/go/bin:/mnt/c/Users/jay/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/jay/go/bin:/mnt/c/Users/jay/AppData/Roaming/npm:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)

________________________________________________________
Executed in  134.64 millis    fish           external
   usr time    0.01 millis   13.00 micros    0.00 millis
   sys time   18.94 millis  184.00 micros   18.75 millis
```

**Comment by mehalter** [comment] 2023-03-03 04:09
yeah this is definitely unrelated to AstroNvim. We will leave AstroNvim how it is for now. Thanks for looking into this @jay-babu !

**Comment by jay-babu** [comment] 2023-03-03 05:01
There is a caveat, like someone who doesn't have those tools installed and doesn't want that functionality, astronvim will cause additional latency regardless of their preference and there is no way to opt out unlike all the user customization options

**Comment by jay-babu** [comment] 2023-03-03 05:03
`maps.n["<leader>gg"] = { function() vim.fn.executable "lazygit" == 1 && toggle_term_cmd "lazygit" end, desc = "ToggleTerm lazygit" }`, I think this would be the best option with no latency it is lazily executed and if the result of `vim.fn.executable "lazygit"` is cached, unsure what your thoughts are on that

**Comment by mehalter** [comment] 2023-03-03 05:53
@jay-babu are you changing the shell in Neovim? There are a lot of reports that fish is extremely slow for Neovim anyway. The results of that call I don't think are cached in a way that you would like, just the function itself. So the latency would end up being worse. I don't think AstroNvim can protect against stuff like that in every case where some people's machines might be slow at some operations. This also would make the code a lot less easy to maintain and the bindings will not go away when the tools are not available. I'm not really wanting to make this change

**Comment by Uzaaft** [comment] 2023-03-03 07:31
Oh, if You’re using fish then you should for sure change it.
Also: this has nothing to do with with astronvim, but with how your wsl instance is setup.

**Comment by Zevan770** [comment] 2025-05-06 13:59
related [`executable()` is slow on WSL · Issue #31506 · neovim/neovim](https://github.com/neovim/neovim/issues/31506)
