### ISSUE TITLE
Cannot update NvChad/nvim-colorizer and files are not colorized

### ISSUE THREAD

**Issue by Morette** [AstroNvim/AstroNvim#959] opened 2022-09-10 18:04 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

1.9.2

### Neovim version (>= 0.7)

NVIM v0.8.0-dev-1049-g040559439

### Operating system/version

Ubuntu 22.04

### Describe the bug

Files are not being colorized. When I try to update the plugin, got an error for NvChad/nvim-colorizer.lua

### Steps to Reproduce

1. nvim;
2. :AstroUpdate then quit Astro;
3. :PackerSync;

### Expected behavior

All plugins are installed/updated correctly

### Screenshots

![image](https://user-images.githubusercontent.com/20028647/189496083-79a64137-ca91-4712-a277-490815d1f995.png)

**Comment by mehalter** [comment] 2022-09-10 18:24
There are a few things about this. 1. I see that you are using an unofficial version of Neovim which is not supported by AstroNvim in any way and can cause many issues due to broken changes for an unreleased and unsupported Neovim. 2. This is a duplicate of #957

**Closed** 2022-09-10 18:24 UTC
Labels: bug, duplicate, invalid
