### ISSUE TITLE
Failed to run `config` for telescope.nvim

### ISSUE THREAD

**Issue by armada45-pixel** [AstroNvim/AstroNvim#1783] opened 2023-04-17 20:30 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows 11 V.22H2 22621.1555

### Terminal/GUI

powershell 7.3.3

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.10.3
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `explorer` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- WARNING `python/python3` is not installed: Used for mappings to pull up python REPL (Optional)

// I already install python 3.11.3

### Describe the bug

Error show first time when call live grep.
![image](https://user-images.githubusercontent.com/59261678/232601260-106257f4-1876-4228-bb87-9116f15957ce.png)
![image](https://user-images.githubusercontent.com/59261678/232601322-1a43a110-3ba9-4b82-be1b-008e9cda880f.png)

### Steps to Reproduce

1. Call live grep. <leader> - f - w **First time after open vim.**
2. Run :lazy build telescope.nvim. **First time after open vim.**

### Expected behavior

Using without error noti half of screen.
![image](https://user-images.githubusercontent.com/59261678/232602494-c96025d9-7f09-4cfa-87e9-c25a8a481d18.png)

### Screenshots

![image](https://user-images.githubusercontent.com/59261678/232603089-b644be44-e55f-4bcc-b764-848cc710c3a9.png)

**Comment by mehalter** [comment] 2023-04-17 20:38
Duplicate of #1699

**Closed by mehalter** 2023-04-17 20:38 UTC
Labels: bug

**Comment by armada45-pixel** [comment] 2023-04-18 05:42
https://github.com/AstroNvim/AstroNvim/issues/58#issuecomment-1483882011
For me.
`make` command not working. After i execute it said `make: Nothing to be done for 'all'.`
In my case if using make must running terminal in administrator mode and execute `make clean` and `make`

Or using `cmake`
`cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release && cmake --build build --config Release && cmake --install build --prefix build`
ref https://github.com/nvim-telescope/telescope-fzf-native.nvim#vim-plug
