### ISSUE TITLE
`clangd` conflicts with `clang-format`

### ISSUE THREAD

**Issue by ChrisMGeo** [AstroNvim/AstroNvim#2014] opened 2023-06-19 20:14 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Windows 22H2 (OS Build 19045.3086)

### Terminal/GUI

Windows Terminal

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.24.1
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `explorer` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I installed `clang-format` using Mason to help format my java code. However whenever I'm editing C (i haven't tried with C++), `clang-format` and `clangd` conflict with each other with the following message:
`warning: multiple different client offset_encodings detected for buffer, this is not supported yet.`
Uninstalling `clang-format` gets rid of the problem.

### Steps to Reproduce

1. Install both `clang-format` and `clangd`
2. Edit a C file

### Expected behavior

If possible one should take precendence over formatting?

**Comment by mehalter** [comment] 2023-06-19 20:47
This is not actually coming from having both installed. You can have both installed, your `clangd` is just not properly configured. Duplicate of #1013

Also `clangd` already provides formatting with `clang-format` out of the box so you actually can just remove `clang-format`. If you want to have both and just not use `clangd` for formatting then here is the documentation for configuring formatting: https://astronvim.com/Recipes/advanced_lsp#controlling-formatting

**Closed by mehalter** 2023-06-19 20:47 UTC
Labels: bug
