### ISSUE TITLE
Treesitter node error for javascript files

### ISSUE THREAD

**Issue by agdt3** [AstroNvim/AstroNvim#2444] opened 2024-02-01 17:40 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.2.1

### Terminal/GUI

iterm2

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim
- AstroNvim Version: v3.42.2
- Neovim Version: v0.9.5
- OK Using stable Neovim >= 0.8.0
- OK git is installed: Used for core functionality such as updater and plugin management
- OK open is installed: Used for gx mapping for opening files with system opener (Optional)
- WARNING lazygit is not installed: Used for mappings to pull up git TUI (Optional)
- OK node is installed: Used for mappings to pull up node REPL (Optional)
- WARNING gdu-go is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
- OK python is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Updated AstroVim to v3.42.2 and updated packages
When opening javascript files, getting a treesitter error:
```
Error executing vim.schedule lua callback: ...im/0.9.5/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 616 for language javascrip
t
stack traceback:
        [C]: in function '_ts_parse_query'
        ...im/0.9.5/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'load_query'
        ...y/aerial.nvim/lua/aerial/backends/treesitter/helpers.lua:65: in function 'get_query'
        ...lazy/aerial.nvim/lua/aerial/backends/treesitter/init.lua:22: in function 'is_supported'
        ...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:40: in function 'is_supported'
        ...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:73: in function 'get_best_backend'
        ...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:147: in function 'get'
        ...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:251: in function 'attach'
        .../share/nvim/lazy/aerial.nvim/lua/aerial/autocommands.lua:88: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Ran `TSUpdate javascript`, but that didn't fix the error.

Output of `:checkhealth nvim-tresitter`
```
nvim-treesitter: require("nvim-treesitter.health").check()

Installation
- OK tree-sitter found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
- OK node found v18.17.1 (only needed for :TSInstallFromGrammar)
- OK git executable found.
- OK cc executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "22.3.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000"
}

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
```

### Steps to Reproduce

Run `:AstroUpdate`

### Expected behavior

No js error.

**Comment by mehalter** [comment] 2024-02-01 17:43
Duplicate of #1673

**Closed by mehalter** 2024-02-01 17:43 UTC
Labels: bug, duplicate

**Comment by agdt3** [comment] 2024-02-01 17:48
@mehalter Given that I've tried to re-install the javascript parser already, is this a treesitter issue?

**Comment by mehalter** [comment] 2024-02-01 17:49
Yeah this is unrelated to AstroNvim. Sorry!

**Comment by tariqbaater** [comment] 2024-02-02 18:57
> @mehalter Given that I've tried to re-install the javascript parser already, is this a treesitter issue?

did you find any solutions for this issue?

**Comment by vcfvct** [comment] 2024-02-04 23:32
Also getting this error after a `AstroUpdate`, it was not there previously. 
Kind of annoying as it pops up each time opening a js file. 
Any possible fix for it? :) 

Thanks.

**Comment by mehalter** [comment] 2024-02-04 23:44
@vcfvct It's coming from aerial (or other plugins that haven't updated to the breaking changes in treesitter yet). They have been fixed upstream but haven't been tagged in a release. You can unpin aerial for now if you want to get it early. I've pushed the dev to tag a new release to have it in a stable release.

**Comment by mehalter** [comment] 2024-02-04 23:48
@vcfvct I went ahead and just tagged a manual pinning to the specific aerial commit out of their release cycle and tagged [v3.42.4](https://github.com/AstroNvim/AstroNvim/releases/tag/v3.42.4). Once they tag a new release I will do another patch release to get us back on following stable releases of Aerial.

**Comment by vcfvct** [comment] 2024-02-05 21:59
> @vcfvct I went ahead and just tagged a manual pinning to the specific aerial commit out of their release cycle and tagged [v3.42.4](https://github.com/AstroNvim/AstroNvim/releases/tag/v3.42.4). Once they tag a new release I will do another patch release to get us back on following stable releases of Aerial.

Awesome, Thank you so much @mehalter . I verified the error is gone. 👍
