### ISSUE TITLE
Error updating from 3.0.1 to 3.2.1

### ISSUE THREAD

**Issue by dgrbrady** [AstroNvim/AstroNvim#1644] opened 2023-03-15 12:47 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu 20.04

### Terminal/GUI

Ubuntu terminal

### AstroNvim Health

```
astronvim: require("astronvim.health").check()                                  
    2 ========================================================================        
    3 ## AstroNvim                                                                    
    4   - INFO: AstroNvim Version: v3.0.1                                             
    5   - INFO: Neovim Version: v0.8.3                                                
    6   - OK: Using stable Neovim >= 0.8.0                                            
    7   - OK: `git` is installed: Used for core functionality such as updater and plugin management
    8   - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
    9   - WARNING: `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
   10   - OK: `node` is installed: Used for mappings to pull up node REPL (Optional)  
   11   - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
   12   - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
   13   - OK: `python3` is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

When trying to update from 3.0.1, I get this error and the update fails

```
Update available to v3.2.1
Updating requires a restart, continue?
(y/n) y




Error running command: git -C /home/dbrady/.config/nvim config branch.HEAD.remote
Error message:

Error executing Lua callback: /home/dbrady/.config/nvim/lua/astronvim/utils/git.lua:76: attempt to concatenate local 'remote' (a nil value)
stack traceback:
        /home/dbrady/.config/nvim/lua/astronvim/utils/git.lua:76: in function 'remote_url'
        /home/dbrady/.config/nvim/lua/astronvim/utils/updater.lua:121: in function 'create_rollback'
        /home/dbrady/.config/nvim/lua/astronvim/utils/updater.lua:249: in function 'update'
        /home/dbrady/.config/nvim/lua/astronvim/autocmds.lua:234: in function </home/dbrady/.config/nvim/lua/astronvim/autocmds.lua:234>
```

### Steps to Reproduce

1. Run `:AstroUpdate`
2. Type `y` when prompted to continue
3. See error

### Expected behavior

AstroNvim should be updated to latest version

**Comment by mehalter** [comment] 2023-03-15 12:49
Duplicate of #1616

**Closed by mehalter** 2023-03-15 12:49 UTC
Labels: bug
