### ISSUE TITLE
E492: Not an editor command: PackerSync

### ISSUE THREAD

**Issue by aleXOR2** [AstroNvim/AstroNvim#921] opened 2022-08-27 15:24 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

19.0

### Neovim version (>= 0.7)

0.7.2

### Operating system/version

Debian GNU/Linux 10 (buster)

### Describe the bug

I follow installation steps:
```
$ git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim
$ nvim +PackerSync
E492: Not an editor command: PackerSync
```
Not quite sure why latest nvim can't recognize config folder...

### Steps to Reproduce

I follow installation steps:
```
$ git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim
$ nvim +PackerSync
E492: Not an editor command: PackerSync
```
Not quite sure why latest nvim can't recognize config folder...

### Expected behavior

It runs ok

**Comment by aleXOR2** [comment] 2022-08-27 15:35
I fix the bug by changing :
`XDG_CONFIG_HOME`

previously it was:
```
$ echo $XDG_CONFIG_HOME
/home/alexor2/.configkde
```
I think it is worth to add to install instructions:
assuming $XDG_CONFIG_HOME is ~/.config or unset

**Comment by mehalter** [comment] 2022-08-29 00:27
Since this is not a bug with AstroNvim I will go ahead and close this. I will add a not about this in the documentation website.

**Closed by mehalter** 2022-08-29 00:27 UTC
Labels: bug
