### ISSUE TITLE
Error "symbol not found" on nvim start in compute_foldcolumn

### ISSUE THREAD

**Issue by vVolodya** [AstroNvim/AstroNvim#2321] opened 2023-10-04 02:00 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS Sonoma 14.0

### Terminal/GUI

Warp

### AstroNvim Health

 AstroNvim
 -·AstroNvim·Version:·v3.37.1
 -·Neovim·Version:·v0.9.2
 -·OK·Using·stable·Neovim·>=·0.8.0
 -·OK·git·is·installed:·Used·for·core·functionality·such·as·updater·and·plugin·management
 -·OK·open·is·installed:·Used·for·gx·mapping·for·opening·files·with·system·opener·(Optional)
 -·OK·lazygit·is·installed:·Used·for·mappings·to·pull·up·git·TUI·(Optional)
 -·OK·node·is·installed:·Used·for·mappings·to·pull·up·node·REPL·(Optional)
 -·WARNING·gdu·is·not·installed:·Used·for·mappings·to·pull·up·disk·usage·analyzer·(Optional)
 -·WARNING·btm·is·not·installed:·Used·for·mappings·to·pull·up·system·monitor·(Optional)
 -·OK·python3·is·installed:·Used·for·mappings·to·pull·up·python·REPL·(Optional)

### Describe the bug

When starting nvim, i receive the following error message

`
E5108: Error executing lua ...dya/.config/nvim/lua/astronvim/utils/status/provider.lua:77: dlsym(RTLD_DEFAULT, compute_foldcolumn): symbol not found
stack traceback:
        [C]: in function '__index'
        ...dya/.config/nvim/lua/astronvim/utils/status/provider.lua:77: in function 'provider'
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:381: in function '_eval'
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:398: in function '_eval'
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:398: in function '_eval'
        ...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:473: in function <...hare/nvim/lazy/heirline.nvim/lua/heirline/statusline.lua:472>
`

### Steps to Reproduce

1. Type "nvim ." in some project folder with files
2. Receive the error message
3. Open / close fold column - error message
4. Open new file - error message

### Expected behavior

No error

### Additional Context

I can skip the error by pressing Q multiple times, but every time i open / close the folder column or open new file i receive the error again.

I have the same setup on my windows WSL2 machine, did `:AstroUpdate`, everything works just fine.

Also i tried to hard code the width value in provider.lua to supress the error, it worked but layout was not flexible anymore :)

**Comment by kukot** [comment] 2023-10-04 04:35
I can confirm that I am getting the same error
![image](https://github.com/AstroNvim/AstroNvim/assets/67894193/144f284a-2e66-4de1-a4a5-08083a09ae43)

**Comment by mehalter** [comment] 2023-10-04 04:55
Duplicate of #2311

**Closed by mehalter** 2023-10-04 04:55 UTC
Labels: bug
