### ISSUE TITLE
Problems about options when vue file formats code

### ISSUE THREAD

**Issue by TickHeart** [AstroNvim/AstroNvim#955] opened 2022-09-09 06:03 UTC
### Question

When I write a vue file, there will be an automatic formatting code when I save it, but he has the options of' volar' and' null-ls'. I don't want this. I want the default to be' null-ls'。

I hope to get your help, and I'm grateful.

![image](https://user-images.githubusercontent.com/66043405/189281866-63e026bf-df45-43c3-b233-61981883fc65.png)

**Comment by mehalter** [comment] 2022-09-09 09:54
Duplicate of #775

**Closed** 2022-09-09 09:55 UTC
Labels: duplicate, question
