### ISSUE TITLE
Warning message after update to latest version of Astronvim

### ISSUE THREAD

**Issue by duytrung** [AstroNvim/AstroNvim#2642] opened 2024-06-29 13:49 UTC
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue
- [X] I have run `:Lazy update` and are on the latest version of AstroNvim
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Operating system/version

Windows 10

### Terminal/GUI

Windows Terminal

### AstroNvim Health

![image](https://github.com/AstroNvim/AstroNvim/assets/2046672/f2af20ea-d3f9-48da-834d-fd1e1bb75c43)

### Describe the bug

startup nvim and encountered the messages:

![image](https://github.com/AstroNvim/AstroNvim/assets/2046672/2646b0a0-042f-4c10-8c4c-8d76800fdf50)

### Steps to Reproduce

1. type nvim in command console.
2. nvim started up and showed the messages as above
3. 

### Expected behavior

nvim usually not displaying such message

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/2046672/2bd1c81b-d51a-466b-a360-07027c084616)

### Additional Context

I tried to run nvim -u repro.lua. Then found neovim started to download plugins and AstroNvim started as usual.

I exit nvim and run "nvim" again the error displayed as in Screenshot above.

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment] 2024-06-29 13:51
When you say you "exited and ran `nvim` again", do you mean you ran `nvim -u repro.lua`? If not then you were just relaunching your own configuration again and not the reproduction configuration

**Comment by mehalter** [comment] 2024-06-29 13:52
Based on the error messages it looks completely unrelated to core AstroNvim code. Maybe share your configuration or make sure the `repro.lua` you provided actually replicates the bug

**Comment by mehalter** [comment] 2024-06-29 15:05
I have verified that astronvim does not have any of these errors. The words `mkdnflow` and `luarocks` are nowhere in the entire AstroNvim organization and the issue cannot be replicated with the provided `repro.lu`. I will go ahead and close this since it's part of the user configuration. If you have ongoing questions a good place to ask would be the AstroNvim Discord. If you do more digging and think this is reproducible in some way and update the issue I can re-open this.

**Closed by mehalter** 2024-06-29 15:05 UTC
Labels: bug, can't replicate
