### ISSUE TITLE
Error loading LuaSnip after installing astronvim

### ISSUE THREAD

**Issue by silvergama** [AstroNvim/AstroNvim#2548] opened 2024-04-21 04:57 UTC
After following all the installation instructions for astronvim as per the official documentation, I am facing an issue when loading the LuaSnip plugin. Upon starting Neovim, I receive the following error:

```
Error detected while processing {user}/.config/nvim/init.lua: 
Failed to source `{user}/.local/share/nvim/lazy/LuaSnip/plugin/luasnip.vim` 
vim/_editor.lua:0: {user}/.config/nvim/init.lua..nvim_exec2() called at {user}/.config/nvim/init.lua:0../{user}/.local/share/nvim/lazy/LuaSnip/plugin/luasnip.vim, line 1: Vim(function):E488: Trailing characters: ^M
```
![4602738B-AFC2-4049-85C2-57AC1E954DF7](https://github.com/AstroNvim/AstroNvim/assets/14098038/9a2dd8a6-01f7-4c4a-b47a-ccb5311aa80b)
![8F5ED6C9-766F-41FF-B2FA-1C4458A53A91](https://github.com/AstroNvim/AstroNvim/assets/14098038/6da3ab7a-5f68-4993-87a9-7f4785714a15)
![546B9366-6A25-4C59-9968-420D220EE66F_1_102_o](https://github.com/AstroNvim/AstroNvim/assets/14098038/703a7366-0861-4414-8bce-46bf3bb6ad7a)

Installed astronvim following the instructions in the official documentation.

Any help to resolve this issue would be greatly appreciated. Thank you!
Note: My Mac is an M1.

**Comment by mehalter** [comment] 2024-04-21 09:43
Please provide your configuration and succinct steps to reproduce the error

**Comment by mgierada** [comment] 2024-04-30 06:46
Looks like a nvim-treesitter issue. Did you raise an issue there? Usually, all treesitter issues are gone with `TSUpdate` or `TSInstall <parser>`

**Comment by mehalter** [comment] 2024-05-08 18:33
I'm fairly certain this isn't related to AstroNvim and has to do with probably the user's git client trying to fix line endings on clone potentially or at the very least an issue with luasnip. Not sure which. I'm going to go ahead and close this since there isn't any actionable items needed on the AstroNvim side.

**Closed by mehalter** 2024-05-08 18:33 UTC
Labels: can't replicate
