### ISSUE TITLE
Conflict of keyboard shortcuts between Neo-Tree and alpha-nvim

### ISSUE THREAD

**Issue by TestProgger** [AstroNvim/AstroNvim#926] opened 2022-08-29 03:30 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

1.9.0-3-g8581efa

### Neovim version (>= 0.7)

NVIM 0.7.2

### Operating system/version

ArchLinux. Kernel 5.19.3

### Describe the bug

When I press the <leader>d key combination in Neo-Tree an error pops up and further use of vim is not possible with each subsequent press and error.

Removing the lines associated with alphanvim from the file lua/core/mappings.lua problem solved.

-- Alpha
if is_available "alpha-nvim" then maps.n["<leader>d"] = { "<cmd>Alpha<cr>", desc = "Alpha Dashboard" } end

### Steps to Reproduce

1. Open Neo-Tree [ <leader>o ]
2. Move the cursor to the beginning of the line with the desired file name
3. Press <leader>d
4. Catch an error

### Expected behavior

Error executing Lua callback : .../alpa.nvim:559: Cursor position outside the buffer

### Screenshots

![Screenshot_2022-08-29_03-16-35](https://user-images.githubusercontent.com/36998526/187116907-b041c02b-ac25-4479-9afc-902082d4a790.png)

**Comment by mehalter** [comment] 2022-08-29 14:45
As I understand this is not a bug with the mappings conflicting at all, but there is a bug with Alpha in relation to a new feature in `neo-tree`. Hopefully this gets some traction and is fixed by Alpha. (https://github.com/nvim-neo-tree/neo-tree.nvim/issues/490)

**Closed by mehalter** 2022-08-29 14:45 UTC
Labels: bug
