### ISSUE TITLE
nvim does not work after latest mac os update

### ISSUE THREAD

**Issue by TahaBinhuraib** [AstroNvim/AstroNvim#1340] opened 2022-11-17 14:14 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

latest versioon

### Neovim version (>= 0.8)

nvim 0.8.1

### Operating system/version

macos ventura

### Describe the bug

Packer sync and clean dont work

### Steps to Reproduce

update to latest macos version and open nvim

### Expected behavior

Packer sync and packer clean don't work

### Additional Context

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/69626776/202468851-608ad02f-c8bd-43ef-a6b6-e9f57644cc4a.png">

**Comment by mehalter** [comment] 2022-11-17 14:24
can you share your user config? Did you just update from a version below v2.6.5 and follow the announcement guides? It looks like there is probably some caching issues and you need to refresh your cache

**Comment by justisGipson** [comment] 2022-11-17 17:27
i might be dealing with something similar. Recently updated things, on macos latest and as of this morning no Packer commands are working. _very new to all things vim_ so this could be on me, but no configs have changed

**Comment by justisGipson** [comment] 2022-11-17 17:34
@mehalter i had missed that thread. 🙏🏼 many thanks.

**Comment by mehalter** [comment] 2022-11-18 15:36
Given that this description says "Packer sync and clean dont work" I'm thinking this is a duplicate of the pinned issue I have linked. I am going to go ahead and close this as a duplicate. @TahaBinhuraib let me know if this isn't the same!

**Closed by mehalter** 2022-11-18 15:36 UTC
Labels: bug, can't replicate
