### ISSUE TITLE
The code is deformed when scrolling

### ISSUE THREAD

**Issue by nappalm** [AstroNvim/AstroNvim#1566] opened 2023-02-06 00:53 UTC
### Checklist

- [x] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.11.8

### Neovim version (>= 0.8)

0.8.0

### Operating system/version

Windows 11

### Describe the bug

When I do Control + d to scroll down, the code is completely deformed

### Steps to Reproduce

Open file in Nvim
Press control + d to scroll down
[bug] ?

### Expected behavior

Show the code without deforming when scrolling

### Screenshots

![image](https://user-images.githubusercontent.com/35016608/216857797-8266a5bf-4c93-439f-b3cc-3c91c710a12e.png)

**Comment by mehalter** [comment] 2023-02-10 16:46
Can you replicate this without any user configuration?

**Comment by mehalter** [comment] 2023-02-25 13:53
What terminal are you using @gembancud @nappalm

**Comment by azinsharaf** [comment] 2023-02-25 14:09
I've seen this in wsl as well not in scrolling but in resizing the terminal (even alacritty).

**Comment by mehalter** [comment] 2023-02-25 17:02
Any idea what could be causing it @azinsharaf ? Seems probably unrelated to AstroNvim's code 🤔

**Comment by azinsharaf** [comment] 2023-02-25 17:17
i can't reproduce it with astronvim v3 and don't have v2 to test it. (tested on both alacritty and windows terminal. using WSL1 on Win 11 VM hosted on Macbook M1)
ctrl-d and ctrl-d work fine. That would be helpfull if they run it in terminal with verbose mode.

**Comment by mehalter** [comment] 2023-02-25 20:38
Ok cool @azinsharaf I'll leave this open until v3 is released and we can see if people still have the issues 🤷

**Comment by mehalter** [comment] 2023-03-01 15:04
@nappalm if you could try out the new v3 `nightly` release and see if you still have the same issue? @azinsharaf I believe has said that they haven't gotten the issue since using v3

**Comment by mehalter** [comment] 2023-03-10 15:42
I think this is resolved in the new stable release. I  am going to go ahead and close this. Let me know if this still pops up and I can reopen it!

**Closed by mehalter** 2023-03-10 15:42 UTC
Labels: bug, can't replicate
