### ISSUE TITLE
Heirline flickering on .tex files with Vimtex installed

### ISSUE THREAD

**Issue by Bahnschrift** [AstroNvim/AstroNvim#1124] opened 2022-10-18 02:04 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v2.3.0

### Neovim version (>= 0.8)

NVIM v0.8.0-1210-gd367ed9b2

### Operating system/version

Ubuntu 22.04.1 LTS on Windows 11

### Describe the bug

Since the introduction of heirline, I've had issues with the statusbar flickering when typing in insert mode in .tex files. I opened [this issue](https://github.com/lervag/vimtex/issues/2518) on the vimtex issue tracker, but since I'm unable to replicate with a minimal nvim installation and heirline config, I believe the issue is caused by the heirline config used here.

### Steps to Reproduce

Add `["lervag/vimtex"] = {},` to `plugins.lua` and begin editing a `.tex` file in insert mode.

### Expected behavior

Heirline statusbar not flickering on input.

### Screenshots

![Flickering](https://user-images.githubusercontent.com/31170809/196143508-55f4699e-5072-418f-9a99-fdf4fc1cd771.gif)

### Additional Context

I've tried setting vimtex to load strictly before or after heirline, but it didn't seem to help. There is no flickering in non `.tex` files and the flickering does not occur without vimtex installed. I've also tried commenting out all components of the statusbar in `heirline_opts` in `heirline.lua`, but that doesn't seem to help. The issue is also not terminal-specific - I've tried with both Windows Terminal and regular command prompt.

**Comment by mehalter** [comment] 2022-10-18 02:25
This is a really unfortunate bug in Neovim currently upstream where the cursor jumps it the statusline when `cmdheight=0`. There is an open PR to resolve this. Hopefully it is finished in time for 0.8.1. In the mean time, the best work around for this is to add `cmdheight = 1` to the `options.opt` table in the `user/init.lua` (docs page for this: https://astronvim.github.io/Recipes/cmdheight)

https://github.com/neovim/neovim/pull/20582

**Comment by mehalter** [comment] 2022-10-18 02:28
Since we sadly can't do anything to resolve this, I'm going to go ahead and close this as not planned. Please test without `cmdheight=1` and see if that resolves it. I've been considering making `cmdheight=1` the default since there are still some instabilities at least until these things are at least fixed. Do you think this would be a good move for now and have users opt into the `cmdheight=0`?

**Closed** 2022-10-18 02:28 UTC
Labels: bug, upstream

**Comment by mehalter** [comment] 2022-10-18 02:29
Also @Bahnschrift I did notice you aren't using the official release of Neovim 0.8 and are still using the unreleased `nightly` build. You could also try with Neovim 0.8 stable to see if it is better, but it probably won't be fully fixed. I would definitely recommend updating regardless to a stable release. Many bug fixes were merged in prior to the release.

**Comment by Bahnschrift** [comment] 2022-10-18 02:36
Thanks for all the help. `cmdheight = 1` definitely fixed it. I'm not really sure what other issues `cmdheight = 0` causes so I can't really say if it would be necessary to make `cmdheight = 1` the default. Maybe some warning in the [documentation](https://astronvim.github.io/Recipes/cmdheight) would suffice?

I don't think I am actually using the nightly build of Neovim. I think the extra version info from `nvim --version` is a product of using the `.appimage` instead of installing the package with the `.deb`.

**Comment by mehalter** [comment] 2022-10-18 02:39
Oh you are totally correct. That's super weird, I would think the app image would still do the correct indication for the version, but yeah the commit version does match perfectly. Also I agree, a warning would be a good idea. I'll add that tomorrow :) thanks for your help!

**Comment by mehalter** [comment] 2022-10-18 02:40
If the issue reports for cmdheight weirdness continue we can readdress changing the default ! I really like when the cmdheight is 0 but I also want to provide a super solid/stable base for everyone

**Comment by krishnakumarg1984** [comment] 2022-10-19 21:24
I can confirm that with vimtex, cmdheight=0 is completely broken, and heirline starts flickering badly. I had opened an issue with vimtex a few days ago about this.

https://github.com/lervag/vimtex/issues/2516

**Comment by krishnakumarg1984** [comment] 2022-11-04 11:00
>I really like when the cmdheight is 0 but I also want to provide a super solid/stable base for everyone

@mehalter Are we still keeping `cmdheight=0` in the `nightly`? What's the decision on this?
