### ISSUE TITLE
Getting some kind of LSP error every time I open neovim

### ISSUE THREAD

**Issue by an1ndra** [AstroNvim/AstroNvim#732] opened 2022-07-05 19:29 UTC
When I open nvim prog.lua, this error appears.
![Screenshot from 2022-07-06 00-54-18](https://user-images.githubusercontent.com/36324543/177401308-7094da76-ae94-4838-bb15-86879e3f5532.png)

**Comment by mehalter** [comment] 2022-07-05 19:33
Duplicate of #667

**Closed as completed by mehalter** 2022-07-05 19:33 UTC
Labels: duplicate, question
