### ISSUE TITLE
invalid node type at position 1109 for language c

### ISSUE THREAD

**Issue by Shaun289** [AstroNvim/AstroNvim#2254] opened 2023-08-30 05:39 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu 20.04

### Terminal/GUI

Terminator

### AstroNvim Health

$ nvim --version
NVIM v0.9.1

# Astro nvim version
9ea4eaa 2023-08-27 19:23 Micah Halter chore(snapshot): update `lazy_snapshot`   (grafted, HEAD -> main, tag: v3.36.6, origin/main, origin/HEAD)

### Describe the bug

```
Error executing vim.schedule lua callback: ...6w0L/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 1109 for language c
stack traceback:
        [C]: in function '_ts_parse_query'
        ...6w0L/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get_query'
        ...nvim/lazy/nvim-treesitter/lua/nvim-treesitter/indent.lua:98: in function 'fn'
        ...nvim/lazy/nvim-treesitter/lua/nvim-treesitter/indent.lua:76: in function 'get_indents'
        ...nvim/lazy/nvim-treesitter/lua/nvim-treesitter/indent.lua:150: in function 'get_indent'
        ...lazy/indent-blankline.nvim/lua/indent_blankline/init.lua:476: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue
```

I got this message every moment with .c file.
I can do nothing.

### Steps to Reproduce

Just open .c file

### Expected behavior

Do not repeat the messages and can edit .c files.

### Screenshots

![스크린샷, 2023-08-30 14-37-15](https://github.com/AstroNvim/AstroNvim/assets/15827001/e9fd8026-8120-4344-b3cc-38db2ac57094)

**Comment by mehalter** [comment] 2023-08-30 10:55
Duplicate of #1673

**Closed by mehalter** 2023-08-30 10:55 UTC
Labels: bug
