### ISSUE TITLE
How to set catppuccin flavor to be permanent?

### ISSUE THREAD

**Issue by marko-kriska** [AstroNvim/AstroNvim#929] opened 2022-08-29 16:57 UTC
Hi, imho you should not touch anything outside your `lua/user` folder but use the config machinery astrovim provides:

1. copy the `lua/user_example` folder to `lua/user` if not done so yet.
2. in `lua/user/init.vim` add:

```lua
   plugins = {
		init = {
			"catppuccin/nvim",
	(...)
```
3. nvim +PackerSync -> you'll see it downloaded and installed
4. configure:

```lua
local config = {
	-- Set colorscheme
	--colorscheme = "default_theme",
	colorscheme = "catppuccin",
```

PS: Nice colorscheme, love it ;-)

_Originally posted by @AXGKl in https://github.com/AstroNvim/AstroNvim/issues/221#issuecomment-1081514218_

**Comment by marko-kriska** [comment] 2022-08-29 16:59
I have done the above and it works great! Now I would like to set Catppucin mocha as a flavor, and also permanenty!

**Comment by mehalter** [comment] 2022-08-29 17:06
Duplicate of #221. For future reference @marko-kriska can we please keep discussions in the same thread to keep the knowledge aggregated. In case someone else wants to know how to supply options to `catppuccin` or similar themes. Anyway, you are looking for the `options` table. See the user_example for more context and examples:

```lua
return {
  options = {
    g = {
      catppuccin_flavour = "macchiato",
    },
  },
  colorscheme = "catppuccin",
  plugins = {
    init = {
      { "catppuccin/nvim", as = "catppuccin", config = function() require("catppuccin").setup() end },
    },
  },
}
```

**Closed by mehalter** 2022-08-29 17:06 UTC

**Comment by marko-kriska** [comment] 2022-08-29 18:06
I can do it "on the fly" via :Catppuccin <flavour>, but don't know how to implement in /user/init.lua!

**Comment by mehalter** [comment] 2022-08-29 18:08
Please check out the code block I have included above @marko-kriska . It includes everything necessary for setting the flavour of catppuccin in the `user/init.lua` file :)

**Comment by marko-kriska** [comment] 2022-08-29 18:34
Success! Thank you! :)
