### ISSUE TITLE
Failed to update NvChad/nvim-colorizer.lua

### ISSUE THREAD

**Issue by f73** [AstroNvim/AstroNvim#957] opened 2022-09-09 20:30 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

Version: v1.9.2

### Neovim version (>= 0.7)

NVIM v0.7.2

### Operating system/version

Linux/Arch Linux

### Describe the bug

Running `:PackerSync` returns `Failed to update NvChad/nvim-colorizer.lua`

### Steps to Reproduce

`:PackerSync`

### Expected behavior

Succesfull update of all packages available for update.

### Screenshots

![Screenshot from 2022-09-09 22-28-03](https://user-images.githubusercontent.com/16547841/189437669-08e2270d-24f7-468b-bfa8-ac74a148f732.png)

**Comment by seanschade** [comment] 2022-09-09 21:34
`rm -rf ~/.config/local/share/nvim` resolved it for me.

**Comment by mehalter** [comment] 2022-09-10 00:23
Thanks for the comment @seanschade that's correct! This is a limitation due to packer and force pushes overwriting commit logs in their plugin. While it's annoying and unfortunate, it's not a bug in AstroNvim. So I'm going to go ahead and close this.

**Closed** 2022-09-10 00:24 UTC
Labels: bug, upstream

**Comment by f73** [comment] 2022-09-10 07:16
Ok, removing just offending app from `.local/share/nvim/site/pack/packer/opt/` solved it, as removing whole nvim dir for me removes undos, recents and what not. Thanks for solution!
