### ISSUE TITLE
Treesitter comment strings broken in recent AstroNvim version 

### ISSUE THREAD

**Issue by oryband** [AstroNvim/AstroNvim#1991] opened 2023-06-11 10:08 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu 22.10 ; Neovim installed via snap

### Terminal/GUI

Alacritty

### AstroNvim Health

```
==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.22.0
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

Recent nvim-tresitter version breaks comment strings in multiple languages. In practice it means I can't code in Python because of consistent error virtual hover text popping up everywhere.

Suggestion:
1. Pin down nvim-treesitter and dependent plugins according to its release tags (currently latest is from Apr 10 and tagged v0.9.0
2. Make `:Astronvim update` to automatically update Treesitter parsers and queries.

### Steps to Reproduce

See:
1. https://github.com/nvim-treesitter/nvim-treesitter/issues/4925
2. https://github.com/nvim-treesitter/nvim-treesitter/issues/4910
1. https://github.com/nvim-treesitter/nvim-treesitter/issues/3092

### Expected behavior

Comment strings should not produce errors.

**Comment by mehalter** [comment] 2023-06-11 19:05
What error are you getting?

**Comment by mehalter** [comment] 2023-06-11 19:07
Oh I see, I believe this is a duplicate of #1990. I'll go ahead and close

**Closed** 2023-06-11 19:07 UTC
Labels: bug, duplicate

**Comment by oryband** [comment] 2023-06-12 06:06
hi, thanks for responding. i can't seem to fix the issue, can you help me resolve this? I updated all treesitter parsers and queries and the issue still persists. i am currently forced to pin treesitter to an old version just so I could use astronvim.

regardless, why isn't astronvim pinning versions, at least for major plugins like treesitter? it could help with avoiding breaking changes such as these

**Comment by mehalter** [comment] 2023-06-12 14:06
We could definitely pin treesitter to major versions. The main thing is treesitter only releases versions with each Neovim release. So it happens maybe twice a year. Also the versions do not follow semantic versioning, they simply match the Neovim version. So it doesn't actually fit into the semantic versioning tracking model. We pin all plugins that actually implement semantic versioning releases

**Comment by mehalter** [comment] 2023-06-12 14:06
I am out of town until Thursday, so I can definitely get back to check it on Thursday and help you out
