### ISSUE TITLE
"Symbol not found" bug on macOS Sonoma

### ISSUE THREAD

**Issue by Infonautica** [AstroNvim/AstroNvim#2322] opened 2023-10-05 20:04 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 14.0 (23A344)

### Terminal/GUI

iTerm2

### AstroNvim Health

It fails to render it, see attached screenshot

### Describe the bug

AstroNvim crashes almost on every action i do (open file structure, search for files, etc.). It defenitelly was not the case when i used previous macOS version. After encountering the issue i made a complete reinstallation of the macOS:
- Reset macOS completelly
- Installed iTerm2
- Installed Node
- Installed brew
- Installed AstroNvim

Issue remained with the same error even on the clean system.
I then installed nightly version and it worked much better with only couple of places crashing (like `<leader>fw`)

### Steps to Reproduce

1. Install macOS Sonoma
2. Install AstroNvimm
3. Open AstroNvim
4. Do basic things like `<leader>e` or `<leader>fw`
5. See an exception

### Expected behavior

Expected behavior is that features are working without throwing exceptions

### Screenshots

Some basic comand like `<leader>e`:
<img width="1440" alt="Screenshot 2023-10-05 at 22 49 14" src="https://github.com/AstroNvim/AstroNvim/assets/5521648/b47e0842-e030-41af-a25d-90a744b67c4f">

Result of `:checkhealth astronvim`:
<img width="1440" alt="Screenshot 2023-10-05 at 22 53 47" src="https://github.com/AstroNvim/AstroNvim/assets/5521648/16898137-87ed-45d4-b5d7-ea887c1af230">

Video demonstration:

https://github.com/AstroNvim/AstroNvim/assets/5521648/a4d347ce-67fb-4385-b076-c8ebe9dcebf1

**Comment by mehalter** [comment] 2023-10-05 20:05
Duplicate of https://github.com/AstroNvim/AstroNvim/issues/2311

**Closed by mehalter** 2023-10-05 20:05 UTC
Labels: bug
