### ISSUE TITLE
Lsp autostart no work

### ISSUE THREAD

**Issue by neo-clon** [AstroNvim/AstroNvim#822] opened 2022-08-03 22:12 UTC
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [x] `:PackerSync`
- [x] `:AstroUpdate`
- [x] restarted AstroNvim
- [x] Neovim version >= 0.7.0

**Describe the bug**
After update to mason, lsp isnt autostart

**To Reproduce**
1. Backup config 
2. Download latest version from github
3. Install rust_analyzer lsp server
4. Restart neovim
5. Open rust project

**Expected behavior**
Lsp server auto start when detect file

**Screenshots**
![image](https://user-images.githubusercontent.com/12282168/182721359-356c1f62-190a-4465-84aa-a42d4a24d146.png)
![image](https://user-images.githubusercontent.com/12282168/182721438-45bcdd18-bd41-4b26-8cc7-4d155e8cb04d.png)

**Comment by mehalter** [comment] 2022-08-04 12:28
I see it recognizes `/home/jcervantes/workspace/aumpi_projects/aumpi` as the root directory. Do you have either a `.git` folder, Cargo directory, or a `rust-project.json` file in that directory? the native lsp looks for either of those two files/folders to know when to auto start rust-analyzer.

Here is the relevant code in the `nvim-lspconfig` specification for `rust_analyzer`: https://github.com/neovim/nvim-lspconfig/blob/47a521e621570da77e25c31988e2b74412db25e4/lua/lspconfig/server_configurations/rust_analyzer.lua#L50-L54

**Comment by mehalter** [comment] 2022-08-04 12:36
@neo-clon also this is a duplicate of this issue: #591

**Closed by mehalter** 2022-08-04 12:36 UTC
Labels: question
