### ISSUE TITLE
Getting error while opening .env file

### ISSUE THREAD

**Issue by Uri2001** [AstroNvim/AstroNvim#2350] opened 2023-10-28 05:16 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Ubuntu 22.04

### Terminal/GUI

Window terminal

### AstroNvim Health

   2   astronvim: require("astronvim.health").check()
   3
   4   AstroNvim
   5   - AstroNvim Version: v3.37.7
   6   - Neovim Version: v0.9.4
   7   - OK Using stable Neovim >= 0.8.0
   8   - OK git is installed: Used for core functionality such as updater and plugin management
   9   - OK xdg-open is installed: Used for gx mapping for opening files with system opener (Optional)
  10   - OK lazygit is installed: Used for mappings to pull up git TUI (Optional)
  11   - OK node is installed: Used for mappings to pull up node REPL (Optional)
  12   - WARNING gdu is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  13   - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
  14   - OK python3 is installed: Used for mappings to pull up python REPL (Optional)
  15

### Describe the bug

While opening .env file error appears:
```
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 195 for language bash
stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get'
        ...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:114: in function 'new'
        /usr/local/share/nvim/runtime/lua/vim/treesitter.lua:61: in function '_create_parser'
        /usr/local/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser'
        ...lazy/aerial.nvim/lua/aerial/backends/treesitter/init.lua:50: in function 'fetch_symbols'
        ...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:129: in function 'attach'
        ...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:149: in function 'get'
        ...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:251: in function 'attach'
        .../share/nvim/lazy/aerial.nvim/lua/aerial/autocommands.lua:88: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Steps to Reproduce

1. run nvim .env

### Expected behavior

Get rid of this error

**Comment by mehalter** [comment] 2023-10-28 06:42
Duplicate of #1673

**Closed by mehalter** 2023-10-28 06:42 UTC
Labels: bug

**Comment by Uri2001** [comment] 2023-10-28 07:52
This solution did not help.

**Comment by mehalter** [comment] 2023-10-28 09:55
You should be running `:TSInstall bash` to reinstall  the bash parser since the error you have is regarding the bash.

**Comment by Uri2001** [comment] 2023-10-28 10:22
Thanks alot!
I've got how it works now!

**Comment by mehalter** [comment] 2023-10-28 11:41
No problem. In the future. When there is a duplicate issue. Please continue the discussion in the original issue. We mark duplicate and close as not planned to localize discussion for people coming across the same issue. It's easier to read a single thread rather than 30 threads about the same question
