### ISSUE TITLE
When writing code, the status line bar will flicker when using the tab to select code suggestions.

### ISSUE THREAD

**Issue by zou2699** [AstroNvim/AstroNvim#2255] opened 2023-08-30 07:51 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS  12.6

### Terminal/GUI

Iterm2

### AstroNvim Health

astronvim: require("astronvim.health").check()

## AstroNvim ~
- AstroNvim Version: v3.36.4
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

When writing code, the status line bar will flicker when using the tab to select code suggestions.

### Steps to Reproduce

1. writing code
2. using the tab to select code suggestions.

### Expected behavior

 status line bar not flicker

**Comment by luxus** [comment] 2023-08-30 09:27
you have a bug in your userconfig

**Comment by mehalter** [comment] 2023-08-30 10:59
Duplicate of #1962.

**Closed** 2023-08-30 10:59 UTC
Labels: bug
