### ISSUE TITLE
Not detecting config

### ISSUE THREAD

**Issue by shubhamku044** [AstroNvim/AstroNvim#2519] opened 2024-04-04 07:49 UTC
I have a fork of this AstroNvim repository, today I created a update branch in my repo and added your main config, but it is giving some error
![image](https://github.com/AstroNvim/AstroNvim/assets/77788249/8b24335c-2fe9-49ca-b761-177c3e6c2a85)

[https://github.com/shubhamku044/AstroNvim/tree/update](https://github.com/shubhamku044/AstroNvim/tree/update)

**Comment by mehalter** [comment] 2024-04-04 09:54
Duplicate of #2518

**Closed by mehalter** 2024-04-04 09:54 UTC
