### ISSUE TITLE
Error while opening nvim

### ISSUE THREAD

**Issue by shubhamku044** [AstroNvim/AstroNvim#2325] opened 2023-10-08 08:18 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 14

### Terminal/GUI

alacritty, kitty

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: unknown
- Neovim Version: v0.9.2
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Whenever I am opening my nvim, I am getting this error

### Steps to Reproduce

1. Open any project with neovim
2. in the bottom where we write :wq command, you will see the error

### Expected behavior

This error should not be shown

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/77788249/5841bdff-518d-4fa1-84ce-821851ee6038)

**Comment by mehalter** [comment] 2023-10-08 09:55
Duplicate of #2311

**Closed by mehalter** 2023-10-08 09:55 UTC
Labels: bug
