### ISSUE TITLE
Error when closing an unfocused buffer by pressing on the X icon on a loaded session

### ISSUE THREAD

**Issue by Zeioth** [AstroNvim/AstroNvim#1989] opened 2023-06-10 03:35 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Arch (btw)

### Terminal/GUI

foot

### AstroNvim Health

  astronvim: require("astronvim.health").check()
   3   
   4   AstroNvim
   5   - AstroNvim Version: v3.22.0
   6   - Neovim Version: v0.9.1
   7   - OK Using stable Neovim >= 0.8.0
   8   - OK git is installed: Used for core functionality such as updater and plugin management
   9   - OK xdg-open is installed: Used for gx mapping for opening files with system opener (Optional)
  10   - WARNING lazygit is not installed: Used for mappings to pull up git TUI (Optional)
  11   - OK node is installed: Used for mappings to pull up node REPL (Optional)
  12   - OK gdu is installed: Used for mappings to pull up disk usage analyzer (Optional)
  13   - WARNING btm is not installed: Used for mappings to pull up system monitor (Optional)
  14   - OK python is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

After loading a previously saved session, unfocused buffers fail to be closed with the X tab icon.

    "bufdelete.nvim: No buffers were deleted"

### Steps to Reproduce

1. Open several files, and save them.
2. Reopen AstroNvim and open the last session.
4. Without focusing a tab, try to close it by presing the X icon of the tab.
5. It will fail to close with the error `bufdelete.nvim: No buffers were deleted`.

* I've noticed if I focus the tab (even if I unfocus it later) I can close it correctly. 
* My interpretation is neovim-session-manager load a reference to the buffers, but it doesn't actually load the buffer into memory unless the user focus the buffer.

### Expected behavior

The user should be able to close a buffer without errors under any circumstance.

### Screenshots

![screenshot_2023-06-10_05-30-22_477716671](https://github.com/AstroNvim/AstroNvim/assets/3357792/cc562810-97e6-4135-a54a-51d31a1aaaab)

### Additional Context

Tested on an unmodified fresh AstroNvim installation.

**Comment by mehalter** [comment] 2023-06-10 03:46
Everything you said is correct. This is actually a bug with bufdelete that I have had a PR open to fix for a bit: https://github.com/famiu/bufdelete.nvim/pull/42

Sadly the best we can do is open a PR upstream that fixes this since we can't do anything about it here in AstroNvim. Hopefully this PR gets merged. Thanks for reporting to help us stay up to date!

**Closed by mehalter** 2023-06-10 03:46 UTC
Labels: bug, upstream

**Comment by mehalter** [comment] 2023-06-10 03:47
Also this is a duplicate of #1359

**Comment by Zeioth** [comment] 2023-06-10 03:58
I've forked your fork and indeed it seems to fix the issue. Thank you so much for looking into it.
