### ISSUE TITLE
File Syntax Highlighting Broken with new NeoVim 0.8.0 version

### ISSUE THREAD

**Issue by ismet55555** [AstroNvim/AstroNvim#1034] opened 2022-10-03 04:05 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

1.9.0

### Neovim version (>= 0.7)

0.8.0

### Operating system/version

macOS 12.6 (on Apple M1)

### Describe the bug

- I ran `brew install neovim` which installed NeoVim 0.8.0. Note that brew only has this one version available!
- I went through all steps here: https://astronvim.github.io/#-setup
- When opening a python file (`.py`) there is not syntax highlighting
- I have used AstroNvim with NeoVim 0.7.2 without any issues.
- I'm going to guess that there are breaking changes with the LSP in new NeoVim 0.8.0
    - https://github.com/neovim/neovim/releases/tag/v0.8.0
- `:checkhealth` all looks good

### Steps to Reproduce

1. `brew install neovim`
2. Go through steps: https://astronvim.github.io/#-setup
3. Open a Python .py file

### Expected behavior

Syntax highlighting working

### Additional Context

- **NOTE:** I am able to run `:set filetype=python` which enables syntax highlighting, however I get some error in the banner `[LSP] Accessing client.resolved_capabilities is depreciated ......`

**Comment by mehalter** [comment] 2022-10-03 04:30
Duplicate of #1028

**Closed by mehalter** 2022-10-03 04:30 UTC
Labels: bug
