### ISSUE TITLE
AstroUpdate error

### ISSUE THREAD

**Issue by mhimranhossain** [AstroNvim/AstroNvim#1052] opened 2022-10-08 09:22 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

V2.0.0

### Neovim version (>= 0.7)

NVIM v0.8.0

### Operating system/version

win 11 22h2

### Describe the bug

AstroUpdate error

### Steps to Reproduce

write :AstroUpdate in normal mode and press enter

### Expected behavior

shows user Astrovim is UpToDate or not.

### Screenshots

![image](https://user-images.githubusercontent.com/50992812/194700082-e552bd0c-25d7-4cae-98d2-ecec07ba0dc7.png)

### Additional Context

Everything is up to date with clean install. in stock settings.
![image](https://user-images.githubusercontent.com/50992812/194700934-ecc2a0aa-5bd0-494b-9f83-db8afea6a5a5.png)

git status 
On branch main
Your branch is up to date with 'origin/main'.
nothing to commit, working tree clean

_installed using this from astronvim.github.io_
```
git clone https://github.com/AstroNvim/AstroNvim $env:LOCALAPPDATA\nvim
nvim +PackerSync
```

**Comment by mehalter** [comment] 2022-10-11 19:39
@mhimranhossain are you still running into this? I'm not sure why this would be happening. It looks like your git status isn't resolving tag names 🤔 I've tested this a bunch to try and replicate this and I'm wondering if it has to do with a small hiccup I made when I release v2.0.0 and accidentally deleted the nightly branch and needed to recreate it. So I wonder if this  is resolved now that the repo has settled down a bit

**Comment by alex289** [comment] 2022-10-13 14:50
I can confirm the error is still there, even after manually pulling changes

**Comment by mehalter** [comment] 2022-10-13 15:16
@alex289 if you go into your terminal and go to the `~/.config/nvim` folder (or wherever your astronvim clone is and run `git tag -l --sort=version:refname 'v*'` what do you get as the output?

**Comment by alex289** [comment] 2022-10-13 15:21
```
❯ git tag -l --sort=version:refname 'v*'
v1.0.0
v1.1.0
v1.2.0
v1.3.0
v1.4.0
v1.4.1
v1.4.2
v1.4.3
v1.4.4
v1.5.0
v1.5.1
v1.5.2
v1.6.0
v1.6.1
v1.7.0
v1.8.0
v1.8.1
v1.9.0
v1.9.1
v1.9.2
v1.10.0
v2.0.0
v2.0.1
v2.0.2
v2.1.0
v2.1.1
v2.2.0
v2.2.1
```

And I just manually pulled to the latest version. The problem appears for me only on windows tho. Not Mac

**Comment by mehalter** [comment] 2022-10-13 16:08
@alex289 could you run the same command in Windows?

**Comment by mehalter** [comment] 2022-10-13 16:13
hm, could you try running a few things in a session of AstroNvim?

```
:lua print(require("core.utils.git").latest_version(nil, "v*"))
```

and 

```
:lua vim.pretty_print(require("core.utils.git").get_versions("latest"))
```

**Comment by alex289** [comment] 2022-10-13 17:20
:lua print(require("core.utils.git").latest_version(nil, "v*")) : `nil`

:lua vim.pretty_print(require("core.utils.git").get_versions("latest")) : `{}`

**Comment by mehalter** [comment] 2022-10-13 17:22
how fascinating. The `get_versions("latest")` or `get_versions("v*")` is running the exact command you ran in windows before 🤔 and it did return correctly. This is the output I get on linux:

```
➤ git tag -l --sort=version:refname 'v*'
v1.0.0
v1.1.0
v1.2.0
v1.3.0
v1.4.0
v1.4.1
v1.4.2
v1.4.3
v1.4.4
v1.5.0
v1.5.1
v1.5.2
v1.6.0
v1.6.1
v1.7.0
v1.8.0
v1.8.1
v1.9.0
v1.9.1
v1.9.2
v1.10.0
v2.0.0
v2.0.1
v2.0.2
v2.1.0
v2.1.1
v2.2.0
v2.2.1
```

**Comment by mehalter** [comment] 2022-10-13 17:23
I wonder why it's not parsing correctly when the output gets passed to neovim hmmmmmmmmmmmmmmmm

**Comment by mehalter** [comment] 2022-10-13 17:26
What do you get if you run this:

```
:lua print(vim.fn.system("git -C " .. vim.fn.stdpath("config") .. " tag -l --sort=version:refname 'v*'"))
```

on your windows machine?

**Comment by alex289** [comment] 2022-10-13 17:27
Just for information, this is the output on a Mac:

:lua print(require("core.utils.git").latest_version(nil, "v*")) : `v2.2.1`

:lua vim.pretty_print(require("core.utils.git").get_versions("latest")) : `{ "v1.0.0", "v1.1.0", "v1.2.0", "v1.3.0", "v1.4.0", "v1.4.1", "v1.4.2", "v1.4.3", "v1.4.4", "v1.5.0", "v1.5.1", "v1.5.2", "v1.6.0", "v1.6.1", "v1.7.0"
, "v1.8.0", "v1.8.1", "v1.9.0", "v1.9.1", "v1.9.2", "v1.10.0", "v2.0.0", "v2.0.1", "v2.0.2", "v2.1.0", "v2.1.1", "v2.2.0", "v2.2.1" }`

git tag -l --sort=version:refname 'v*' 
```
v1.0.0
v1.1.0
v1.2.0
v1.3.0
v1.4.0
v1.4.1
v1.4.2
v1.4.3
v1.4.4
v1.5.0
v1.5.1
v1.5.2
v1.6.0
v1.6.1
v1.7.0
v1.8.0
v1.8.1
v1.9.0
v1.9.1
v1.9.2
v1.10.0
v2.0.0
v2.0.1
v2.0.2
v2.1.0
v2.1.1
v2.2.0
v2.2.1
```

**Comment by mehalter** [comment] 2022-10-13 17:28
@alex289 not sure if you saw my message before you sent yours, but could you try running the command in neovim that I sent above on your windows machine?

**Comment by alex289** [comment] 2022-10-13 17:29
> What do you get if you run this:
> 
> ```
> :lua print(vim.fn.system("git -C " .. vim.fn.stdpath("config") .. " tag -l --sort=version:refname 'v*'"))
> ```
> 
> on your windows machine?

This is really weird. It doesnt output anything. On the top right corner is an error icon but I dont know if this is related

**Comment by mehalter** [comment] 2022-10-13 17:30
Hm, but if you run the git command in a windows terminal it works directly? That's super strange 🤔

**Comment by mehalter** [comment] 2022-10-13 17:31
what do you get if you run `:lua print(vim.fn.stdpath("config"))`?

**Comment by mehalter** [comment] 2022-10-13 17:32
Could you try running in the windows terminal as well:

```
git -C <path_to_astronvim_install> tag -l --sort=version:refname 'v*'
```

and replace the <path_to_astronvim_install> with the direct path to the installation

**Comment by mehalter** [comment] 2022-10-13 17:33
Also sorry for all the messages, debugging over github issues is tricky :joy:

**Comment by mehalter** [comment] 2022-10-13 17:33
This is extremely useful though and I really appreciate your help!

**Comment by alex289** [comment] 2022-10-13 17:34
> 

`C:\Users\My username\AppData\Local\nvim` which should be the correct path

**Comment by mehalter** [comment] 2022-10-13 17:34
so if you run 

```
git -C C:\Users\My username\AppData\Local\nvim tag -l --sort=version:refname 'v*'
```

does that command work in the windows terminal?

**Comment by alex289** [comment] 2022-10-13 17:35
> Could you try running in the windows terminal as well:
> 
> ```
> git -C <path_to_astronvim_install> tag -l --sort=version:refname 'v*'
> ```
> 
> and replace the <path_to_astronvim_install> with the direct path to the installation

```
v1.0.0
v1.1.0
v1.2.0
v1.3.0
v1.4.0
v1.4.1
v1.4.2
v1.4.3
v1.4.4
v1.5.0
v1.5.1
v1.5.2
v1.6.0
v1.6.1
v1.7.0
v1.8.0
v1.8.1
v1.9.0
v1.9.1
v1.9.2
v1.10.0
v2.0.0
v2.0.1
v2.0.2
v2.1.0
v2.1.1
v2.2.0
v2.2.1
```

**Comment by mehalter** [comment] 2022-10-13 17:35
Ok that's good, what do you get in neovim if you run

```
:lua print(vim.fn.stdpath("config"))
```

**Comment by alex289** [comment] 2022-10-13 17:36
> This is extremely useful though and I really appreciate your help!

Love to help :D

**Comment by alex289** [comment] 2022-10-13 17:36
> 

`C:\Users\My username\AppData\Local\nvim` again

**Comment by mehalter** [comment] 2022-10-13 17:37
how crazy, ok what about this:

```
:lua print(vim.fn.system("git -C C:\Users\My username\AppData\Local\nvim tag -l --sort=version:refname 'v*'"))
```

**Comment by mehalter** [comment] 2022-10-13 17:38
oh, I think I know what it is o.O it's these backslashes that need to be escaped :joy:

**Comment by alex289** [comment] 2022-10-13 17:39
> how crazy, ok what about this:
> 
> ```
> :lua print(vim.fn.system("git -C C:\Users\My username\AppData\Local\nvim tag -l --sort=version:refname 'v*'"))
> ```

`E5107: Error loading lua [string ":lua":1: invalid escape sequence near '"git -C C:'` I think so too, backslashes are on windows really confusing to work with

**Comment by mehalter** [comment] 2022-10-13 17:42
ok could you try this

```
:lua print(vim.fn.system("git -C " .. vim.fn.stdpath("config"):gsub("\", "\\") .. " tag -l --sort=version:refname 'v*'"))
```

and see if it works? :)

**Comment by mehalter** [comment] 2022-10-13 17:44
Also I just realized I had a typo, and update the command

**Comment by alex289** [comment] 2022-10-13 17:45
> ok could you try this
> 
> ```
> :lua print(vim.fn.system("git -C " .. vim.fn.stdpath("config"):gsub("\\", "\\\\") .. " tag -l --sort=version:refname 'v*'"))
> ```
> 
> and see if it works? :)

No output again, very weird

**Comment by mehalter** [comment] 2022-10-13 17:49
what do you get when you run this:

```
:lua print(vim.fn.stdpath("config"):gsub("\\", "\\\\"))
```

**Comment by mehalter** [comment] 2022-10-13 17:49
Another thing it could be is the spacing, in the windows terminal do you need to escape the spaces in the filenames?

**Comment by mehalter** [comment] 2022-10-13 17:51
oh wait, what is this 5 at the end? is this just different neovim folders?

**Comment by mehalter** [comment] 2022-10-13 17:51
oh that seems to be the number of replacements hmmmm one sec

**Comment by alex289** [comment] 2022-10-13 17:53
> oh wait, what is this 5 at the end? is this just different neovim folders?

I just checked. There is only one `nvim` folder existing

**Comment by alex289** [comment] 2022-10-13 17:54
> Another thing it could be is the spacing, in the windows terminal do you need to escape the spaces in the filenames?

I dont know. When I want to cd into a directory with a space in the name I tab autocompletes to `cd '.\Folder name\'`

**Comment by mehalter** [comment] 2022-10-13 17:54
oh I see, when you concatenate it shouldn't be a problem. OH I SEE

**Comment by mehalter** [comment] 2022-10-13 17:55
let me try something

**Comment by mehalter** [comment] 2022-10-13 17:55
what if you do this:

```
:lua print(vim.fn.system("git -C '" .. vim.fn.stdpath("config") .. "' tag -l --sort=version:refname 'v*'"))
```

**Comment by alex289** [comment] 2022-10-13 17:57
> what if you do this:
> 
> ```
> :lua print(vim.fn.system("git -C '" .. vim.fn.stdpath("config") .. "' tag -l --sort=version:refname 'v*'"))
> ```

`fatal: cannot change to ''C:\Users\My username\AppData\Local\nvim'': Invalid argument`

**Comment by mehalter** [comment] 2022-10-13 17:58
oh wut :( does it automatically add the `'` :(

ok, let's just do this. Could you run:

:lua print("git -C " .. vim.fn.stdpath("config") .. " tag -l --sort=version:refname 'v*'")

**Comment by alex289** [comment] 2022-10-13 18:00
> :lua print("git -C " .. vim.fn.stdpath("config") .. " tag -l --sort=version:refname 'v*'")

Why is windows so complicated haha

`git -C C:\Users\My username\AppData\Local\nvim tag -l --sort=version:refname 'v*'`

**Comment by mehalter** [comment] 2022-10-13 18:01
how strange, and if you run

```
:lua print("git -C '" .. vim.fn.stdpath("config") .. "' tag -l --sort=version:refname 'v*'")
```

?

**Comment by alex289** [comment] 2022-10-13 18:03
`git -C 'C:\Users\My username\AppData\Local\nvim' tag -l --sort=version:refname 'v*'`

**Comment by mehalter** [comment] 2022-10-13 18:04
hm, did you type the previous command incorrectly per chance? Because that string looks like exactly what we want

```
:lua print(vim.fn.system("git -C '" .. vim.fn.stdpath("config") .. "' tag -l --sort=version:refname 'v*'"))
```

**Comment by mehalter** [comment] 2022-10-13 18:04
or maybe that's just because they are printing it with `'` surrounding it?

**Comment by mehalter** [comment] 2022-10-13 18:05
Just for reference this command with the `'` surrounding the path works on linux as well 🤔

**Comment by alex289** [comment] 2022-10-13 18:05
> hm, did you type the previous command incorrectly per chance? Because that string looks like exactly what we want
> 
> ```
> :lua print(vim.fn.system("git -C '" .. vim.fn.stdpath("config") .. "' tag -l --sort=version:refname 'v*'"))
> ```

I just copy pasted this, so yes I am sure

**Comment by alex289** [comment] 2022-10-13 18:09
> :lua print("git -C " .. vim.fn.stdpath("config") .. " tag -l --sort=version:refname 'v*'")

On Mac too

**Comment by mehalter** [comment] 2022-10-13 18:10
Hmmmmmmmmmmmmmmmmmmm o.O this is so annoying :(

**Comment by alex289** [comment] 2022-10-13 18:11
Feel you, so sorry 😅

**Comment by mehalter** [comment] 2022-10-13 18:14
ok wait.... what if you did this on windows

```
:lua print(vim.fn.system({ "cmd.exe", "/C", "git -C " .. vim.fn.stdpath("config"):gsub("\\", "\\\\") .. " tag -l --sort=version:refname 'v*'" }))
```

**Comment by mehalter** [comment] 2022-10-13 18:14
oh wait, without the `gsub` sorry, updated the command

**Comment by alex289** [comment] 2022-10-13 18:16
No output. Why do I not even get an error or sth

**Comment by mehalter** [comment] 2022-10-13 18:17
did you copy it with or without the gsub? Could you make sure you ran the one without the gsub? I really think this one would work :joy:

**Comment by alex289** [comment] 2022-10-13 18:18
I ran it three times, with terminal restarts and without the gsub 😂

**Comment by mehalter** [comment] 2022-10-13 18:19
if you open `cmd.exe` do you have the `git` command?

**Comment by alex289** [comment] 2022-10-13 18:20
I do sir

**Comment by mehalter** [comment] 2022-10-13 18:20
![image](https://user-images.githubusercontent.com/1591837/195675629-df49117d-de40-4d20-84fd-8d350604d01f.png)

**Comment by alex289** [comment] 2022-10-13 18:23
I wish I could do more, but I dont know a lot about this weird quote dash escaping backslash hell

**Comment by mehalter** [comment] 2022-10-13 18:23
what if you try something super simple to see if this is the correct thing:

```
:lua print(vim.fn.system({"cmd.exe", "/C", "dir"}))
```

or is it `ls`? sorry I don't use windows often

**Comment by alex289** [comment] 2022-10-13 18:24
> what if you try something super simple to see if this is the correct thing:
> 
> ```
> :lua print(vim.fn.system({"cmd.exe", "/C", "dir"}))
> ```
> 
> or is it `ls`? sorry I don't use windows often

This works

```
 Volume in drive C is Windows
 Volume Serial Number is 3A35-1D59
 Directory of C:\Users\Alexander.Konietzko\dev
05.10.2022  11:19    <DIR>          .
05.10.2022  11:19    <DIR>          ..
05.10.2022  10:43    <DIR>          CodeStuff
19.09.2022  08:42    <DIR>          Personal
11.10.2022  10:03    <DIR>          Stuff
               0 File(s)              0 bytes
               5 Dir(s)  128.225.316.864 bytes free
```

**Comment by mehalter** [comment] 2022-10-13 18:27
`:lua print(vim.fn.system({"cmd.exe", "/C", "git"}))`

what about this?

**Comment by alex289** [comment] 2022-10-13 18:28
> lua print(vim.fn.system({"cmd.exe", "/C", "git"}))

This shows the correct git --help information

**Comment by mehalter** [comment] 2022-10-13 18:28
ok, what about just this, super simple git command trying to go to the correct directory:

```
:lua print(vim.fn.system({"cmd.exe", "/C", "git -C " .. vim.fn.stdpath("config") .. " status"}))
```

**Comment by alex289** [comment] 2022-10-13 18:29
```
On branch main
Your branch is up to date with 'origin/main'.
nothing to commit, working tree clean
```

**Comment by mehalter** [comment] 2022-10-13 18:29
If that doesn't work could you just try this directly:

```
:lua print(vim.fn.system({"cmd.exe", "/C", "git -C C:\\Users\\My username\\AppData\\Local\\nvim status"}))
```

**Comment by mehalter** [comment] 2022-10-13 18:30
oh ok, so that actually went to the correct directory o.O

**Comment by mehalter** [comment] 2022-10-13 18:30
```
:lua print(vim.fn.system({"cmd.exe", "/C", "git -C " .. vim.fn.stdpath("config") .. " tag -l"}))
```

what about this? :O

**Comment by alex289** [comment] 2022-10-13 18:31
```
nvim-0.6
v1.0.0
v1.1.0
v1.10.0
v1.2.0
v1.3.0
v1.4.0
v1.4.1
v1.4.2
v1.4.3
v1.4.4
v1.5.0
v1.5.1
v1.5.2
v1.6.0
v1.6.1
v1.7.0
v1.8.0
v1.8.1
v1.9.0
v1.9.1
v1.9.2
v2.0.0
v2.0.1
v2.0.2
v2.1.0
v2.1.1
v2.2.0
v2.2.1
```

**Comment by alex289** [comment] 2022-10-13 18:31
We are getting somewhere

**Comment by mehalter** [comment] 2022-10-13 18:31
ok, what about this:

```
:lua print(vim.fn.system({"cmd.exe", "/C", "git -C " .. vim.fn.stdpath("config") .. " tag -l 'v*'"}))
```

**Comment by alex289** [comment] 2022-10-13 18:33
> ok, what about this:
> 
> ```
> :lua print(vim.fn.system({"cmd.exe", "/C", "git -C " .. vim.fn.stdpath("config") .. " tag -l 'v*'"}))
> ```

Mmh, nothing again :( What is this

**Comment by mehalter** [comment] 2022-10-13 18:34
ok so we know that breaks it, what about this:

```
:lua print(vim.fn.system({"cmd.exe", "/C", "git -C " .. vim.fn.stdpath("config") .. " tag -l --sort=version:refname"}))
```

**Comment by alex289** [comment] 2022-10-13 18:38
> ok so we know that breaks it, what about this:
> 
> ```
> :lua print(vim.fn.system({"cmd.exe", "/C", "git -C " .. vim.fn.stdpath("config") .. " tag -l --sort=version:refname"}))
> ```

```
nvim-0.6
v1.0.0
v1.1.0
v1.2.0
v1.3.0
v1.4.0
v1.4.1
v1.4.2
v1.4.3
v1.4.4
v1.5.0
v1.5.1
v1.5.2
v1.6.0
v1.6.1
v1.7.0
v1.8.0
v1.8.1
v1.9.0
v1.9.1
v1.9.2
v1.10.0
v2.0.0
v2.0.1
v2.0.2
v2.1.0
v2.1.1
v2.2.0
v2.2.1
```

**Comment by mehalter** [comment] 2022-10-13 18:39
okokok, so the final command 🤞🏼 

```
:lua print(vim.fn.system({"cmd.exe", "/C", "git -C " .. vim.fn.stdpath("config") .. ' tag -l --sort=version:refname "v*"'}))
```

:O

**Comment by alex289** [comment] 2022-10-13 18:40
> oh wait that last command worked!! :O
> 
> It should be slightly different, it should not show `neovim-0.6`! :D

Oh sorry, yes. The list begins at v1.0.0. Didnt see this

**Comment by mehalter** [comment] 2022-10-13 18:43
holy moly! it was a problem with single vs double quotes being funky in windoze cmd :O OMG thank you so so much for your time with debugging this! This has been infinitely helpful! I will tag a patch release now! Once I get the new stable version tagged. Could you please pull the latest on `main` and then see if `:AstroUpdate` works? :)))))

I'll drop a comment here when the new release is tagged :)

**Comment by alex289** [comment] 2022-10-13 18:44
Of course, thanks for your effort ❤️ 

single and double quotes should not exist at the same time haha

**Comment by mehalter** [comment] 2022-10-13 18:45
for reals smh, ok the new release is tagged :)

**Comment by mehalter** [comment] 2022-10-13 18:47
OMG Thank you so so so much!!!! I'm going to go ahead and close this ticket. What a wild ride!

**Closed by mehalter** 2022-10-13 18:47 UTC
Labels: bug
