### ISSUE TITLE
Changing the pwd in the File Explorer

### ISSUE THREAD

**Issue by WaelKarkoub** [AstroNvim/AstroNvim#2144] opened 2023-07-19 15:04 UTC
### Is your feature related to a problem?

I'm not sure if this is a bug.

### Describe the new feature

 Let's say the current directory is `home` and I wanna do something like `nvim .config/nvim/lua/user/`. Neotree opens a buffer in the correct directory, but the file explorer `<leader>e` still shows the `home` directory, instead of `.config/nvim/lua/user/`. Is there a way to change this behavior? Thanks!

**Comment by mehalter** [comment] 2023-07-19 15:08
Duplicate of #2006

**Closed by mehalter** 2023-07-19 15:08 UTC
Labels: duplicate, question
