### ISSUE TITLE
Fold icons disappeared after upgrade

### ISSUE THREAD

**Issue by SunHuawei** [AstroNvim/AstroNvim#1347] opened 2022-11-18 07:51 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.7.4

### Neovim version (>= 0.8)

NVIM v0.8.0

### Operating system/version

macOS 12.6.1 (21G217)

### Describe the bug

The fold column shows with config `foldcolumn = "1",` or `foldcolumn = "2",`. But the fold icons are disappeared. 
![image](https://user-images.githubusercontent.com/11191857/202648911-92ad1687-9749-4044-98d5-ed43b3a0b580.png)

After reverting to v2.7.3 and `:AstroReload`, they come back,
![image](https://user-images.githubusercontent.com/11191857/202649151-15bcd543-5b31-49ce-a923-0f677c5c3865.png)

### Steps to Reproduce

1. `:AstroUpdate` or `git checkout v2.7.4`
2. Restart AstroNvim

### Expected behavior

Expect to see the icons of folds
![image](https://user-images.githubusercontent.com/11191857/202649395-3c2c2688-05aa-449a-be22-edb26deaebea.png)

**Comment by mehalter** [comment] 2022-11-18 13:11
Can you please share your user config? These are being set by `nvim-ufo` I'm pretty sure. I can't replicate this without your `nvim-ufo` settings

**Comment by mehalter** [comment] 2022-11-18 13:44
![2022-11-18_08:44:22_screenshot](https://user-images.githubusercontent.com/1591837/202718892-93356418-43fa-44df-b054-9bd2485243f1.png)

I just tried setting up `nvim-ufo` and I cannot replicate this

**Comment by mehalter** [comment] 2022-11-21 13:04
@SunHuawei I can't reproduce this and AstroNvim by default doesn't do anything with `foldcolumn` let me know if you can share your personal configuration and I can take a look to see if I can find any bugs in it. I'm going to go ahead and close this for now since it seems unrelated to the core AstroNvim code.

**Closed by mehalter** 2022-11-21 13:04 UTC
Labels: bug, can't replicate
