### ISSUE TITLE
Highlight matching pairs not work

### ISSUE THREAD

**Issue by laowalter** [AstroNvim/AstroNvim#2228] opened 2023-08-20 06:16 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Gentoo Linux

### Terminal/GUI

Kitty

### AstroNvim Health

astronvim: require("astronvim.health").check()
AstroNvim ~
- AstroNvim Version: v3.36.3
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I think  two bracket matched like  ( _)  should be both highlighted. 

### Steps to Reproduce

Just fresh install without any custom config.
git clone git@github.com:AstroNvim/AstroNvim.git ~/.config/nvim there is no highlight matching pair, I thought this activated in defaults.

### Expected behavior

If the current cursor-under bracket matches another, both brackets should be highlighted.

**Comment by mehalter** [comment] 2023-08-20 09:24
Duplicate of https://github.com/AstroNvim/astrotheme/issues/77

**Closed by mehalter** 2023-08-20 09:24 UTC
Labels: bug

**Comment by mehalter** [comment] 2023-08-20 09:26
This is actually not a bug in AstroNvim, it is doing match highlighting. AstroTheme just had a bug where it's not visible

**Comment by laowalter** [comment] 2023-08-20 12:36
Sorry, I just noticed Astrotheme is located in another git lib.
