### ISSUE TITLE
neovim-session-manager error with `<leader>bc`

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/AstroNvim#1959] opened 2023-06-03 02:29 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macos 13.3.1

### Terminal/GUI

kitty

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.18.0
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

Ression Buffer can't be delete by bDelete.
![image](https://github.com/AstroNvim/AstroNvim/assets/51357674/51a8ce6e-4b64-4cd8-85c3-61be07f4d723)

### Steps to Reproduce

1.  `nvim .` open a project, open some files in buffer.
2. `<leader>q` exit project.
3. `nvim .` and then `<leader>Sl`
4. `<leader>bc` close other buffers
5. found error.

### Expected behavior

close other buffers correct.

**Comment by chaozwn** [comment] 2023-06-03 02:31
and `<leader>c` cause error.
![image](https://github.com/AstroNvim/AstroNvim/assets/51357674/d9d32da1-c137-4eb5-9ba4-7de197b8adf1)

**Comment by mehalter** [comment] 2023-06-03 03:52
Can you try with the latest `nightly`?

**Comment by chaozwn** [comment] 2023-06-03 04:07
> Can you try with the latest `nightly`?

how to do it?

**Comment by chaozwn** [comment] 2023-06-03 04:09
> Can you try with the latest `nightly`?

![image](https://github.com/AstroNvim/AstroNvim/assets/51357674/2f5e423a-e212-4afb-b606-d75dac0dc6ea)

**Comment by mehalter** [comment] 2023-06-03 04:10
You can just set your `updater.lua` file to

```lua
return { channel = "nightly" }
```

and then restart and run `:AstroUpdate`

It looks like you did it

**Comment by chaozwn** [comment] 2023-06-03 04:17
> problem not solved

**Comment by mehalter** [comment] 2023-06-03 04:18
Ah, I cannot replicate on my end. Are you quoting that from somewhere? I don't see it anywhere :joy: The same error? Can you replicate it without your user configuration?

**Comment by mehalter** [comment] 2023-06-03 04:18
whoops that was a mistake

**Comment by chaozwn** [comment] 2023-06-03 04:19
> 
`<leader>Sl` buffer, can you use `<leader>c` to close?

**Comment by chaozwn** [comment] 2023-06-03 04:20
![image](https://github.com/AstroNvim/AstroNvim/assets/51357674/36b38d12-5197-4db1-9c88-629687d7229f)

**Comment by mehalter** [comment] 2023-06-03 04:23
Yes I can @chaozwn can you replicate it with out your user configuration?

**Comment by chaozwn** [comment] 2023-06-03 04:32
> 

yes i used initial configuration but still got error. I'm sorry. the correct reproduce steps:

1. open a session with some buffers. then `<leader>q` quit session.
2. use `<leader>Sl` reopen session.
3. you will found before buffers in tabline.
4. use `<leader>bc` to close other buffers except current.

**Comment by mehalter** [comment] 2023-06-03 04:34
Yeah I cannot replicate the bug @chaozwn are you able to replicate it *without* your user configuration and only enable the resession option?

**Comment by mehalter** [comment] 2023-06-03 04:35
Ah I see, so it's *only* `<leader>bc` and not both `<leader>bc` and `<leader>c`?

**Comment by chaozwn** [comment] 2023-06-03 04:36
> Ah I see, so it's _only_ `<leader>bc` and not both `<leader>bc` and `<leader>c`?

i rm my user dir. and only `<leader>bc` not works. `<leader>c` works normal.

**Comment by mehalter** [comment] 2023-06-03 04:40
Ok, I'll keep investigating next week and let you know if I find anything else

**Comment by mehalter** [comment] 2023-06-03 04:55
@chaozwn I can confirm `<leader>bc` works just fine on my end. Can you please try with a clean user configuration. This can involve not only removing your `user/` folder but also refreshing your cache/data folders. But for now I cannot seem to replicate the error you are having.

**Comment by chaozwn** [comment] 2023-06-03 05:02
> @chaozwn I can confirm `<leader>bc` works just fine on my end. Can you please try with a clean user configuration. This can involve not only removing your `user/` folder but also refreshing your cache/data folders. But for now I cannot seem to replicate the error you are having.

i have rm -rf .local/**/nvim. and retest, still not work.
https://github.com/AstroNvim/AstroNvim/assets/51357674/422dcf0c-a80d-4629-8f33-63d061871999

**Comment by mehalter** [comment] 2023-06-03 13:20
ohhhhhhhhhh @chaozwn I see, this is not coming from `resession`, this is coming from the default session management in AstroNvim. I was able to replicate this appropriately

**Comment by mehalter** [comment] 2023-06-03 13:45
I found the issue upstream and I am following up with it. I will go ahead and close this issue and respond back when I make some progress.

**Closed by mehalter** 2023-06-03 13:45 UTC
Labels: bug, replicated
