### ISSUE TITLE
Want to add fullpath to my statusline, like  set statusline+=%F  

### ISSUE THREAD

**Issue by laowalter** [AstroNvim/AstroNvim#1256] opened 2022-11-05 11:09 UTC
### Question

New to Astronvim, great works!  Have read manual  and the init.lua in custom example, but have no idea on how to add the full path file to statuslins.  

Thanks!

**Comment by mehalter** [comment] 2022-11-05 12:32
Duplicate of #1136

**Closed** 2022-11-05 12:32 UTC
Labels: duplicate, question
