### ISSUE TITLE
Filetype not being detected causing syntax highlighting to fail.

### ISSUE THREAD

**Issue by sjcobb2022** [AstroNvim/AstroNvim#1032] opened 2022-10-02 19:02 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

1.10.0

### Neovim version (>= 0.7)

0.8.0-3

### Operating system/version

EndeavorOS Artemis Nova 22_9

### Describe the bug

After a fresh install of linux, nvim, and astronvim, syntax highlighting is not visible. 

When using `set: filetype=language`, syntax highlighting then appears. This infers that it may be an issue with filetype.lua

I have temporarily installed [nathoms](https://github.com/nathom/filetype.nvim) filetype.nvim which identifies the file correctly.

### Steps to Reproduce

1. Clean install of EndeavourOS (using online installer with XFCE) 
2. Clean install of neovim using pacman (version 0.8.0-3)
3. Open literally any file of any type and provided with no syntax highlighting. Even after installing the LSP and treesitter libraries for whichever language is being used.

### Expected behavior

Syntax highlighting to be present and automatic.

### Screenshots

![image](https://user-images.githubusercontent.com/68509699/193471090-6da2f08d-d7d4-47b1-bf3a-b60065800912.png)

### Additional Context

I also installed NvChad to verify that it wasn't just neovim having this issue and I can confirm that syntax highlighting is functional and file types are detected.

**Comment by mehalter** [comment] 2022-10-02 19:02
Duplicate of #1028

**Closed by mehalter** 2022-10-02 19:02 UTC
Labels: bug
