### ISSUE TITLE
Segmentation fault while saving file

### ISSUE THREAD

**Issue by PantomInach** [AstroNvim/AstroNvim#1694] opened 2023-03-25 12:23 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Void Linux 6.1.21_1

### Terminal/GUI

alacritty + zsh + tmux

### AstroNvim Health

astronvim: require("astronvim.health").check()
========================================================================
## AstroNvim
  - INFO: AstroNvim Version: v3.5.2
  - INFO: Neovim Version: v0.8.3
  - OK: Using stable Neovim >= 0.8.0
  - OK: `git` is installed: Used for core functionality such as updater and plugin management
  - OK: `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
  - WARNING: `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
  - WARNING: `node` is not installed: Used for mappings to pull up node REPL (Optional)
  - WARNING: `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
  - WARNING: `btm` is not installed: Used for mappings to pull up system monitor (Optional)
  - OK: `python` is installed: Used for mappings to pull up python REPL (Optional)

lazy: require("lazy.health").check()
========================================================================
## lazy.nvim
  - OK: Git installed
  - OK: no existing packages found by other package managers
  - OK: packer_compiled.lua not found

man: require("man.health").check()
========================================================================
  - OK: plugin/man.vim not in $VIMRUNTIME
  - OK: autoload/man.vim not in $VIMRUNTIME

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: None

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $COLORTERM='truecolor'

## tmux
  - ERROR: `escape-time` (500) is higher than 300ms
    - ADVICE:
      - set escape-time in ~/.tmux.conf:
          set-option -sg escape-time 10
      - https://github.com/neovim/neovim/wiki/FAQ
  - INFO: Checking stuff
  - WARNING: `focus-events` is not enabled. |'autoread'| may not work.
    - ADVICE:
      - (tmux 1.9+ only) Set `focus-events` in ~/.tmux.conf:
          set-option -g focus-events on
  - INFO: $TERM: xterm-256color
  - ERROR: $TERM should be "screen-256color" or "tmux-256color" in tmux. Colors might look wrong.
    - ADVICE:
      - Set default-terminal in ~/.tmux.conf:
          set-option -g default-terminal "screen-256color"
      - https://github.com/neovim/neovim/wiki/FAQ
  - WARNING: Neither Tc nor RGB capability set. True colors are disabled. |'termguicolors'| won't work properly.
    - ADVICE:
      - Put this in your ~/.tmux.conf and replace XXX by your $TERM outside of tmux:
          set-option -sa terminal-overrides ',XXX:RGB'
      - For older tmux versions use this instead:
          set-option -ga terminal-overrides ',XXX:Tc'

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 3 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - WARNING: Could not load Python 3:
    /bin/python3 does not have the "neovim" module.
    python3.10 not found in search path or not executable.
    python3.9 not found in search path or not executable.
    python3.8 not found in search path or not executable.
    python3.7 not found in search path or not executable.
    /bin/python does not have the "neovim" module.
    - ADVICE:
      - See :help |provider-python| for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_python3_provider = 0` to your init.vim
  - INFO: Executable: Not found

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`, `pnpm`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`, `pnpm`) commands work.

## Perl provider (optional)
  - WARNING: "Neovim::Ext" cpan module is not installed
    - ADVICE:
      - See :help |provider-perl| for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/aaron/.local/state/nvim/lsp.log
  - INFO: Log size: 4527 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14

which_key: health#which_key#check
========================================================================
### Describe the bug

# Error description
Regular segmentation fault when saving to file, resulting in the closing of nvim.

Syslog of error:
```
2023-03-25T10:48:31.74517 kern.info: [ 2125.944500] nvim[14117]: segfault at 7f8e64000 ip 00007f8e81647c21 sp 00007ffe84e4bd70 error 4 in libluv.so.1.43.0[7f8e81645000+32000] likely on CPU 9 (core 1, socket 0)
2023-03-25T10:48:31.74522 kern.info: [ 2125.944518] Code: 48 8d 15 9f f7 02 00 be fe ff ff ff 48 89 ef e8 55 de ff ff b8 01 00 00 00 5b 5d 41 5c c3 0f 1f 00 31 d2 31 f6 e8 ff da ff ff <48> 8b 33 48 89 ef e8 34 f2 ff ff 31 d2 be ff ff ff ff 48 89 ef e8
```

While working on a project with bigger python and latex files (~500 lines), regularly when saving a file, nvim crashes.
Even after removing all lsp/linter/formatter and using a clean `astronvim` installation, nvim still crashed.
Although, this reduces the frequency of crashed.

# Probable error cause
It seems to be connected to the async backend of `lua`/`astronvim` and [`libuv`](https://github.com/luvit/luv) and/or [`luvit`](https://luvit.io/) as the syslog highlights an error in `libluv.so.1.43.0`.
Could be that saving a file asynchronously and also performing another asynchronously read/writte operation (lsp/formatter/linter) results in a segmentation fault originating from `libluv`.

# Other undocumented occurrences of the issue
* Opening a file
* Running lsp/formatter/linter

### Steps to Reproduce

1. Create a (large) `test.tex` file in a directory (Could probably be any filetype)
2. Start nvim with `nvim .`
3. Open the file in a buffer
4. Toggle explorer (Maybe optional)
5. Save one file in fast succession approximately 10–30 times by spamming `<leader> + w` (in my case `<space> + f`)

It seems the issue can be reproduced more easily on bigger files and project structures.
While I managed to reproduce this bug with an empty `test.tex` file, approximately 100 saves were needed before nvim crashed.
On one of my bigger projects, the crash happened regular when saving files.

### Expected behavior

Neovim saves the current file without crashing.

### Screenshots

![Unbenannt](https://user-images.githubusercontent.com/72529530/227714096-35bbfec6-bd69-4424-b2b5-7c6afceb87bd.png)

https://user-images.githubusercontent.com/72529530/227716958-906508a8-3a9a-4840-acd2-ada835c0fe49.mp4

### Additional Context

# Issue still present after following steps
* Removing the `nvim/lua/user` folder
* Removing `~\.local\share\nvim` folder

**Comment by mehalter** [comment] 2023-03-25 14:40
Seems like this is a deeper problem since none of these things are related to the AstroNvim internals. You could disable formatting on save to resolve the issue. Sadly there's not much else we can do when it comes to the performance of the formatter, the performance of the Neovim LSP integration, or the file detection with `libuv`

**Comment by PantomInach** [comment] 2023-03-25 15:24
Thanks for the information. Sadly, even when disabling formatting on save, the issue still occurs.

**Comment by PantomInach** [comment] 2023-03-25 15:35
This problem is probably the same as this [issue](https://github.com/neovim/neovim/issues/22694) from the [`neovim`](https://github.com/neovim/neovim/) repo.

**Comment by mehalter** [comment] 2023-03-25 15:35
Does it happen without language servers running? Can you deduce it to a specific LSP or null-ls source?

**Comment by mehalter** [comment] 2023-03-25 15:36
Ah that makes sense @PantomInach !

**Comment by mehalter** [comment] 2023-03-25 16:45
It appears that that issue makes sense for this. I am going to go ahead and close this issue. Let me know if I should reopen this! Thanks for investigating this deeper to help find the root cause!

**Closed by mehalter** 2023-03-25 16:45 UTC
Labels: bug, upstream
