### ISSUE TITLE
Ability to update core packages?

### ISSUE THREAD

**Issue by ckt114** [AstroNvim/AstroNvim#1599] opened 2023-03-02 00:06 UTC
### Is your feature related to a problem?

How can I update core packages, such as `mason.nvim` per this line? https://github.com/AstroNvim/AstroNvim/blob/main/lua/core/plugins.lua#L195

There's a bug in `mason.nvim` that needs to be updated to be fixed.

### Describe the new feature

N/A

**Comment by mehalter** [comment] 2023-03-02 00:08
Duplicate of #1595

**Closed** 2023-03-02 00:08 UTC
Labels: duplicate, enhancement
