### ISSUE TITLE
v2.2.2 appears to have broken transparency config settings

### ISSUE THREAD

**Issue by Mjb141** [AstroNvim/AstroNvim#1108] opened 2022-10-14 14:45 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v2.2.2

### Neovim version (>= 0.7)

v0.8.0

### Operating system/version

MacOS

### Describe the bug

[Transparency settings](https://github.com/AstroNvim/AstroNvim/issues/8#issuecomment-1276307330) described in that issue don't seem to work as expected now. The background is transparent until you use `space + e` to open the tree, at which point transparency on the main window is replaced by the default theme.

On first open:
![image](https://user-images.githubusercontent.com/46346590/195874597-02800184-0881-4906-8716-e2ad3462c4e6.png)

On opening tree:
![image](https://user-images.githubusercontent.com/46346590/195874801-3a091509-56b4-4ecd-8fa4-6a9ddcd565a3.png)

On opening/starting a file:
![image](https://user-images.githubusercontent.com/46346590/195874928-065d4720-0a9e-435f-86f0-82758de9236e.png)

### Steps to Reproduce

Have these transparency settings in your user config:
```return {
  -- set highlight group for any theme
  -- the key is the name of the colorscheme or init
  -- the init key will apply to all colorschemes
  highlights = {
    -- apply highlight group to all colorschemes (include the default_theme)
    init = {
      -- set the transparency for all of these highlight groups
      Normal = { bg = "NONE", ctermbg = "NONE" },
      CursorColumn = { cterm = {}, ctermbg = "NONE", ctermfg = "NONE" },
      CursorLine = { cterm = {}, ctermbg = "NONE", ctermfg = "NONE" },
      CursorLineNr = { cterm = {}, ctermbg = "NONE", ctermfg = "NONE" },
      LineNr = {},
      SignColumn = {},
      StatusLine = {},
      NeoTreeNormal = { bg = "NONE", ctermbg = "NONE" },
      NeoTreeNormalNC = { bg = "NONE", ctermbg = "NONE" },
    },
  },
}
```

Update to 2.2.2. 

Open tree with `ctrl+o` or `ctrl+e`. 

### Expected behavior

Transparency is unchanged as in previous versions.

**Comment by mehalter** [comment] 2022-10-14 14:47
Duplicate of #8, It's a good idea to keep conversation on the same topic in the same location.

**Closed by mehalter** 2022-10-14 14:47 UTC
Labels: bug
