### ISSUE TITLE
transparency doesn't work well for multiple panes

### ISSUE THREAD

**Issue by azinsharaf** [AstroNvim/AstroNvim#1125] opened 2022-10-18 18:23 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.3.0

### Neovim version (>= 0.8)

0.8.0

### Operating system/version

Windows 11

### Describe the bug

I have used the highlight configuration below and when I use the window split (Ctrl-w n) it only makes the focused window transparent. (see the gif file)

```
        highlights = {
                -- apply highlight group to all colorschemes (include the default_theme)
                init = {
                        -- set the transparency for all of these highlight groups
                        Normal = { bg = "NONE", ctermbg = "NONE" },
                        CursorColumn = { cterm = {}, ctermbg = "NONE", ctermfg = "NONE" },
                        CursorLine = { cterm = {}, ctermbg = "NONE", ctermfg = "NONE" },
                        CursorLineNr = { cterm = {}, ctermbg = "NONE", ctermfg = "NONE" },
                        LineNr = {},
                        SignColumn = {},
                        StatusLine = {},
                        NeoTreeNormal = { bg = "NONE", ctermbg = "NONE" },
                        NeoTreeNormalNC = { bg = "NONE", ctermbg = "NONE" },
                },
        },
```

### Steps to Reproduce

see above

### Expected behavior

both panels should be transparent.

### Screenshots

![neovim](https://user-images.githubusercontent.com/10101468/196513100-d80806e7-bbde-4eca-90be-92249635f747.gif)

**Comment by mehalter** [comment] 2022-10-18 18:31
Duplicate of #8

**Comment by mehalter** [comment] 2022-10-18 18:31
Please check relevant issues as the solution for this has been contributed in the relevant thread.

**Closed by mehalter** 2022-10-18 18:31 UTC
Labels: bug

**Comment by mehalter** [comment] 2022-10-18 18:32
You are missing setting `NormalNC`
