### ISSUE TITLE
After installing astronvim, no syntax highlighting

### ISSUE THREAD

**Issue by dengwenqi123** [AstroNvim/AstroNvim#994] opened 2022-09-22 00:29 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

v1.9.2-1-g9059299

### Neovim version (>= 0.7)

NVIM v0.8.0-dev-1120-ga0e6e767a

### Operating system/version

ubuntu20.04

### Describe the bug

**After installing astronvim, no syntax highlighting**

![image](https://user-images.githubusercontent.com/9389292/191632846-85926c94-1659-4881-bf04-e2c6bf8ad70b.png)

### Steps to Reproduce

Installed with reference to the official documentation
https://astronvim.github.io/

### Expected behavior

Installed with reference to the official documentation
https://astronvim.github.io/

### Screenshots

![image](https://user-images.githubusercontent.com/9389292/191632870-9389c984-eff4-4fba-af04-613315e3d127.png)

**Comment by mehalter** [comment] 2022-09-22 02:28
Duplicate of #960

**Closed by mehalter** 2022-09-22 02:28 UTC
Labels: bug
