### ISSUE TITLE
Some Nerd Icons get rendered as chinese characters and Error Message after install

### ISSUE THREAD

**Issue by aravezskinteeth** [AstroNvim/AstroNvim#2312] opened 2023-09-30 15:49 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS Sonoma 14.0

### Terminal/GUI

kitty

### AstroNvim Health

- AstroNvim Version: v3.37.0
- Neovim Version: v0.9.2
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

#### Symbols rendered as chinese characters

Some nerd icons are getting rendered as chinese characters after installing.
This error occurs as soon after I upgraded to a new M1 MacBook Pro with MacOS Sonoma and after installing and persisted even after cloning my [AstroNvim config](https://github.com/aravezskinteeth/astronvim-config). 

It looks like this

<img width="1371" alt="Screenshot 2023-09-30 at 10 02 56" src="https://github.com/AstroNvim/AstroNvim/assets/104392087/7d254fdf-cbda-46b4-84c2-4ac6e24650fc">

And like this after cloning my config

<img width="1179" alt="Screenshot 2023-09-30 at 10 04 32" src="https://github.com/AstroNvim/AstroNvim/assets/104392087/2cffa682-4c6b-4f03-9bcd-5c704148aba0">

Which is weird bc I'm using the exact same [kitty config](https://github.com/aravezskinteeth/.dotfiles/blob/main/config/kitty/kitty.conf) and installed the same fonts I had.

#### Error after installing 
Also I'm getting the same error as #2311. This is after installing:

<img width="1368" alt="Screenshot 2023-09-30 at 10 03 27" src="https://github.com/AstroNvim/AstroNvim/assets/104392087/e8d56be7-fc30-44ff-9d91-1e00563384cf">

And this is what I get after opening any file:

<img width="1138" alt="Screenshot 2023-09-30 at 10 21 20" src="https://github.com/AstroNvim/AstroNvim/assets/104392087/ef75de1d-cd48-4f46-b835-3c12d630c234">

### Steps to Reproduce

1. Install AstroNvim Requirements
2. Clone the repository: `git clone --depth 1 https://github.com/AstroNvim/AstroNvim ~/.config/nvim && nvim`
3. Clone my AstroNvim config: `git clone https://github.com/aravezskinteeth/astronvim-config ~/.config/nvim/lua/user && nvim`

### Expected behavior

I expected to render the correct nerd icons. And to not get errors.

**Comment by mehalter** [comment] 2023-10-01 02:05
The font configuration is out of the hands of AstroNvim sadly. As for the other part, that is a duplicate as you mentioned, so I'll close this as a duplicate of #2311 to localize discussion moving forward

**Closed by mehalter** 2023-10-01 02:05 UTC
Labels: bug
