### ISSUE TITLE
Treesitter generates a lot of errors on lua files

### ISSUE THREAD

**Issue by 0xAndoroid** [AstroNvim/AstroNvim#2289] opened 2023-09-14 18:03 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.5.2

### Terminal/GUI

iterm2

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.36.10
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

When opening any lua file from astro config I am greeted with a lot of errors.
```
Error executing vim.schedule lua callback: ...im/0.9.1/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 1238
 for language lua
stack traceback:
        [C]: in function '_ts_parse_query'
        ...im/0.9.1/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get'
        ...1/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:110: in function 'new'
        ...r/neovim/0.9.1/share/nvim/runtime/lua/vim/treesitter.lua:61: in function '_create_parser'
        ...r/neovim/0.9.1/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser'
        ...lazy/aerial.nvim/lua/aerial/backends/treesitter/init.lua:50: in function 'fetch_symbols'
        ...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:129: in function 'attach'
        ...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:146: in function 'get'
        ...share/nvim/lazy/aerial.nvim/lua/aerial/backends/init.lua:248: in function 'attach'
        .../share/nvim/lazy/aerial.nvim/lua/aerial/autocommands.lua:85: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Steps to Reproduce

1. Get a clean installation of nvim.
2. go to ~/.config/nvim
3. Open nvim
4. Try to open any .lua file

### Expected behavior

There should not be any errors

### Screenshots

<img width="644" alt="Screenshot 2023-09-14 at 2 01 37 PM" src="https://github.com/AstroNvim/AstroNvim/assets/42178850/149b4997-8c19-4bc3-8649-fd9048ea7f1b">

### Additional Context

I don't see this issue in rust/ts files.

**Comment by mehalter** [comment] 2023-09-14 18:09
Duplicate of #1673

**Closed by mehalter** 2023-09-14 18:09 UTC
Labels: bug
