### ISSUE TITLE
Error inlay in commit message pop up

### ISSUE THREAD

**Issue by BoolPurist** [AstroNvim/AstroNvim#1796] opened 2023-04-20 06:17 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

OS: Fedora Linux 37 (Cinnamon) x86_64 | Kernel: 6.2.10-200.fc37.x86_64

### Terminal/GUI

Alacritty with tmux 

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.10.3
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: /usr/share/nvim/runtime

Performance ~
- OK Build type: RelWithDebInfo

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=\177`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $COLORTERM="truecolor"

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v16.18.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.2.10-200.fc37.x86_64",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Thu Apr  6 23:30:41 UTC 2023"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - css                 ✓ . ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luap                ✓ . . . .
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ . ✓
  - nu                  ✓ ✓ ✓ . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

==============================================================================
provider: health#provider#check

Clipboard (optional) ~
- OK Clipboard tool found: xsel

Python 3 provider (optional) ~
- Using: g:python3_host_prog = "/usr/bin/python3"
- Executable: /usr/bin/python3
- Python version: 3.11.2
- pynvim version: 0.4.3
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV

Ruby provider (optional) ~
- Ruby: ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]
- WARNING `neovim-ruby-host` not found.
  - ADVICE:
    - Run `gem install neovim` to ensure the neovim RubyGem is installed.
    - Run `gem environment` to ensure the gem bin directory is in $PATH.
    - If you are using rvm/rbenv/chruby, try "rehashing".
    - See :help |g:ruby_host_prog| for non-standard gem installations.
    - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

Node.js provider (optional) ~
- Node.js: v16.18.0
- WARNING Missing "neovim" npm (or yarn, pnpm) package.
  - ADVICE:
    - Run in shell: npm install -g neovim
    - Run in shell (if you use yarn): yarn global add neovim
    - Run in shell (if you use pnpm): pnpm install -g neovim
    - You may disable this provider (and warning) by adding `let g:loaded_node_provider = 0` to your init.vim

Perl provider (optional) ~
- WARNING "Neovim::Ext" cpan module is not installed
  - ADVICE:
    - See :help |provider-perl| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: /home/nice_graphic/.local/state/nvim/lsp.log
- Log size: 2766 KB

vim.lsp: Active Clients ~
- No active clients

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: bash       ABI: 14, path: /home/nice_graphic/.local/share/nvim/lazy/nvim-treesitter/parser/bash.so
- OK Parser: css        ABI: 13, path: /home/nice_graphic/.local/share/nvim/lazy/nvim-treesitter/parser/css.so
- OK Parser: lua        ABI: 13, path: /home/nice_graphic/.local/share/nvim/lazy/nvim-treesitter/parser/lua.so
- OK Parser: luap       ABI: 14, path: /home/nice_graphic/.local/share/nvim/lazy/nvim-treesitter/parser/luap.so
- OK Parser: make       ABI: 13, path: /home/nice_graphic/.local/share/nvim/lazy/nvim-treesitter/parser/make.so
- OK Parser: markdown   ABI: 13, path: /home/nice_graphic/.local/share/nvim/lazy/nvim-treesitter/parser/markdown.so
- OK Parser: nu         ABI: 14, path: /home/nice_graphic/.local/share/nvim/lazy/nvim-treesitter/parser/nu.so
- OK Parser: python     ABI: 14, path: /home/nice_graphic/.local/share/nvim/lazy/nvim-treesitter/parser/python.so
- OK Parser: rust       ABI: 14, path: /home/nice_graphic/.local/share/nvim/lazy/nvim-treesitter/parser/rust.so
- OK Parser: toml       ABI: 13, path: /home/nice_graphic/.local/share/nvim/lazy/nvim-treesitter/parser/toml.so

==============================================================================
which-key: require("which-key.health").check()

WhichKey: checking conflicting keymaps ~
- OK No conflicting keymaps found

### Describe the bug

When Astronvim opens up for the git commit message,
I get an error message about a nil value for a plugin.
See picture below for the content of the error message.
Once I press any key then this inlay disappears.

### Steps to Reproduce

1. Do some changes in a git repository. 
2. git add .
3. git commit

### Expected behavior

Not showing me this plugin error message inlay when the prompt for commit message comes up.

### Screenshots

![Screenshot from 2023-04-20 08-05-57](https://user-images.githubusercontent.com/57603453/233273571-d18414e0-5047-46d8-8490-0f3b56e56f4d.png)

**Comment by mehalter** [comment] 2023-04-20 12:44
Duplicate of #1788, could you check the discussion that has happened there and see if you can provide anything to help debug. This problem looks like it's popping up to more and more people :'(

**Closed** 2023-04-20 12:44 UTC
Labels: bug, duplicate
