### ISSUE TITLE
AstonNvim with bash file gives treesitter traceback

### ISSUE THREAD

**Issue by hholst80** [AstroNvim/AstroNvim#2412] opened 2024-01-11 16:33 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Artix amd64

### Terminal/GUI

kitty

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.40.3
- Neovim Version: v0.9.5
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I get a terrible stacktrace when I open a bash script in the Astonvim editor.

### Steps to Reproduce

open the bash file

```bash
#!/bin/bash
cat <<HERE |
File manager              | $(test -f pcmanfm && echo pcmanfm || echo pcmanfm-qt)
HERE

```

### Expected behavior

I should not get a trace.

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/6200749/be7388df-4b69-4c40-abbf-a2df1a415640)

**Comment by mehalter** [comment] 2024-01-11 16:36
Duplicate of #1673

**Closed by mehalter** 2024-01-11 16:36 UTC
Labels: bug

**Comment by hholst80** [comment] 2024-01-11 16:40
Reinstalling TSInstall bash does nothing.  The same error appears?

**Comment by mehalter** [comment] 2024-01-11 16:44
If that's the case, then you should open an issue with Treesitter since the error is unrelated to AstroNvim. Just make sure you formulate a good issue to report it upstream. But I will say I cannot replicate this in a fresh install or with a docker container with a fresh installation, so I'm certain there isn't a bug with the parser with this code blcok at least. So you might want to make sure you are actually reinstalling the bash treesitter parser.

![2024-01-11_11:43:46_screenshot](https://github.com/AstroNvim/AstroNvim/assets/1591837/1ed755cc-fad5-4900-992d-197950c12378)

**Comment by hholst80** [comment] 2024-01-11 17:37
I uninstalled nvim-treesitter (package neovim-nvim-treesitter) since there seemed to be a nvim.treesitter system available in Nvim.  A built-in perhaps?  Anywho, now it opens just fine.

![image](https://github.com/AstroNvim/AstroNvim/assets/6200749/b78bc9eb-0410-4936-86df-0c43b1379e4a)
