### ISSUE TITLE
invalid node type for language c

### ISSUE THREAD

**Issue by lazywhite** [AstroNvim/AstroNvim#2189] opened 2023-07-31 09:22 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

ubuntu 22.10

### Terminal/GUI

terminator

### AstroNvim Health

AstroNvim ~
- AstroNvim Version: v3.34.1
- Neovim Version: v0.9.1
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- WARNING `lazygit` is not installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

## c source file
```
#include <stdio.h>

int max(int x, int y) { return x > y ? x : y; }

int main(void) {
	/* p is pointer to func */
	int (*p)(int, int) = &max;  // &可以省略
	// int a, b, c, d;
	int a = 1, b = 2, c = 3, d;

	/* 与直接调用函数等价d = max(max(a, b), c) */
	d = p(p(a, b), c);

	printf("max: %d\n", d);

	return 0;
}

```
## treesitter error 
```
Error executing vim.schedule lua callback: ...-linux64/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 1109 for language c         
stack traceback:                                                                                                                                                             
        [C]: in function '_ts_parse_query'                                                                                                                                   
        ...-linux64/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get_query'                                                                             
        ...nvim/lazy/nvim-treesitter/lua/nvim-treesitter/indent.lua:98: in function 'fn'                                                                                     
        ...nvim/lazy/nvim-treesitter/lua/nvim-treesitter/indent.lua:76: in function 'get_indents'                                                                            
        ...nvim/lazy/nvim-treesitter/lua/nvim-treesitter/indent.lua:150: in function 'get_indent'                                                                            
        ...lazy/indent-blankline.nvim/lua/indent_blankline/init.lua:476: in function ''                                                                                      
        vim/_editor.lua: in function <vim/_editor.lua:0> 
```

### Steps to Reproduce

just edit that source file

### Expected behavior

shoud have no error

**Comment by mehalter** [comment] 2023-07-31 10:30
Duplicate of #1673. You just need to reinstall your `c` parser with `:TSInstall c`

**Closed by mehalter** 2023-07-31 10:30 UTC
Labels: bug
