### ISSUE TITLE
Neotree/heirline flickering

### ISSUE THREAD

**Issue by Subjective** [AstroNvim/AstroNvim#2250] opened 2023-08-28 22:09 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.4

### Terminal/GUI

kitty

### AstroNvim Health

```
AstroNvim ~
- AstroNvim Version: nightly (v3.36.5-2-g8e9fdd5)
- Neovim Version: v0.10.0-dev-953+g1635c9e75
- WARNING Neovim nightly is not officially supported and may have breaking changes
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)
```

### Describe the bug

Ever since https://github.com/nvim-neo-tree/neo-tree.nvim/commit/38293fe690981aba6cfef5e440f26d8b956d463e, I've started to notice a brief visual flicker where the cursor appears at the top of the Neo-tree buffer momentarily before moving to the correct location. This happens whenever Neotree is opened but is especially apparent when switching to the filesystem source.

Interestingly enough, I cannot reproduce this on a non-astronvim config. I think it may be due to some bad interaction with heirline's winbar, as disabling the winbar completely resolves the issue. I'm not sure why this would be the case though, as other winbar providers (e.g. dropbar.nvim) don't seem to cause any flicker. 

My theory is that heirline updates the winbar as soon as the Neotree filesystem is toggled, but it takes a few milliseconds before Neotree asynchronously loads the actual filesystem and the corresponding winbar source selector. I tried messing around with heirline's `update` autocmd events and setting `buffer_match` conditions, but I wasn't able to fix the issue.

### Steps to Reproduce

1. `:Neotree` or switch to filesystem from another source

### Expected behavior

No flickering

### Screenshots

![Screen Recording 2023-08-22 at 12 20 06 PM](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/56745535/29455ff3-89b0-4f33-9f44-f53e226c8222)

### Additional Context

This is a bit of a weird situation, as both Neotree and heirline seem to be behaving as intended, but having them together causes a bad interaction. In any case, this is a pretty minor issue, and I'm assuming most people don't switch Neotree sources often enough to really notice.

**Comment by mehalter** [comment] 2023-08-28 22:13
Duplicate of #1965

**Comment by Subjective** [comment] 2023-08-28 22:21
@mehalter Hi, I just wanted to let you know that this isn't a duplicate. I'm aware there used to be another flickering bug involving Neotree, but that was fixed some time ago. This is an entirely new issue (albeit with a similar effect) that was introduced around 2-3 weeks ago in https://github.com/nvim-neo-tree/neo-tree.nvim/commit/38293fe690981aba6cfef5e440f26d8b956d463e.

**Comment by mehalter** [comment] 2023-08-28 22:22
The screenshot you sent shows the exact flickering. I have had no proof it has ever actually been solved. I can replicate without AstroNvim

**Comment by mehalter** [comment] 2023-08-28 22:26
I can look more deeply tomorrow and see if this needs to be reopened

**Comment by Subjective** [comment] 2023-08-28 22:30
> I can look more deeply tomorrow and see if this needs to be reopened

Alright, just for reference though, this is the old flickering that was fixed in https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1011
![Screen Recording 2023-08-28 at 3 27 38 PM](https://github.com/AstroNvim/AstroNvim/assets/56745535/7f278fff-8de0-47f4-a25d-a097acc45871)

**Comment by mehalter** [comment] 2023-08-28 22:42
Ah this is actually not because we are putting something in the winbar 😂 it's because we are *not* putting anything in the winbar in that buffer. So the flicker is the winbar going away and then coming back.

**Comment by mehalter** [comment] 2023-08-28 22:43
I will investigate tomorrow, I think this is still a bug upstream but I need to figure out the correct way to formalize it to open an upstream issue

**Comment by mehalter** [comment] 2023-08-29 11:42
Confirmed this is an upstream issue this morning. I will open a relevant PR and follow up here soon

**Closed by mehalter** 2023-08-29 11:42 UTC
Labels: bug, upstream

**Comment by mehalter** [comment] 2023-11-29 15:22
@Subjective this PR for Heirline was finally merged in 🥳 the flicker is gone :)
