### ISSUE TITLE
toggleterm requires an extra click when triggering with <F7>

### ISSUE THREAD

**Issue by itsmenewbie03** [AstroNvim/AstroNvim#2539] opened 2024-04-15 11:15 UTC
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5 release

### Operating system/version

EndeavourOS 2023.11.17

### Terminal/GUI

kitty

### Describe the bug

When opening toggleterm using `<F7>` it prompts `Press ENTER or type command to continue`

### Steps to Reproduce

1. Open a file in a buffer
2. While on normal mode hit `<f7>` 

### Expected behavior

Toggleterm should be opened without the annoying prompt

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/89230263/c3157a98-67ad-4b64-9ebb-c94b6d1ca1f6)

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", branch = "v4", import = "astronvim.plugins" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment] 2024-04-15 11:18
Can you replicate with a base installation of AstroNvim? Please share a minimal configuration that reproduces the problem or at the very least share your own configuration. This is probably because of `cmdheight=0` and a plugin that you have is trying to print something when you open a toggle terminal which is causing the enter prompt. A quick fix is probably running `:set cmdheight=1` and the prompt will go away.

**Comment by mehalter** [comment] 2024-04-15 13:25
I have done a deep dive into this this morning and I'm certain that this is unrelated to the core AstroNvim codebase so I'm going to go ahead and close the issue. Feel free to still comment your user configuration at some point and I can see if I can help debug your configuration. The official discord server is also a great place to ask for help form other users as well! If I dig into your configuration and find that this is a core AstroNvim issue then I can re-open this. Thanks again for reporting!

**Closed by mehalter** 2024-04-15 13:25 UTC
Labels: bug, can't replicate
