### ISSUE TITLE
Pasting doesn't work like normal vim

### ISSUE THREAD

**Issue by half-potato** [AstroNvim/AstroNvim#669] opened 2022-06-19 03:04 UTC
**Checklist**
Please confirm you have run the following commands and restarted Neovim and are encountering the issue with the current latest version of AstroNvim
- [yes ] `:PackerSync`
- [ v1.4.4-8-g416736f ] `:AstroUpdate`
- [ yes ] restarted AstroNvim
- [0.7.0 ] Neovim version >= 0.7.0

**Describe the bug**
"+y -> "+p should copy to buffer, then paste from buffer, but "+y brings up this weird menu that I don't understand and doesn't copy to clipboard. 

**To Reproduce**
1. "+yG
2. New vim instance in new buffer
3. "+p
4. E353 Nothing in register +

**Expected behavior**
It should have yanked the document to the + buffer, which is the clipboard, then pasted it

**Comment by mehalter** [comment] 2022-06-19 03:15
Duplicate of #553

**Closed** 2022-06-19 03:15 UTC
Labels: bug, duplicate
