### ISSUE TITLE
it always show this bug

### ISSUE THREAD

**Issue by newyorkthink** [AstroNvim/AstroNvim#2157] opened 2023-07-22 13:41 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Debian

### Terminal/GUI

alacritty

### AstroNvim Health

![image](https://github.com/AstroNvim/AstroNvim/assets/87791643/632133fe-5503-4f93-996a-696e6a518272)

### Describe the bug

![image](https://github.com/AstroNvim/AstroNvim/assets/87791643/8937956d-96cb-4946-9eb6-2297ae75bc37)

### Steps to Reproduce

![image](https://github.com/AstroNvim/AstroNvim/assets/87791643/4e4b8532-5061-4bf3-b326-69f13f23fe3d)

### Expected behavior

![image](https://github.com/AstroNvim/AstroNvim/assets/87791643/558067c3-f13b-479c-90c2-17cd7c4bef99)

**Comment by mehalter** [comment] 2023-07-22 13:43
Duplicate of https://github.com/AstroNvim/AstroNvim/issues/1699

**Closed by mehalter** 2023-07-22 13:43 UTC
Labels: bug

**Comment by mehalter** [comment] 2023-07-22 13:44
You have already opened this a few days ago (#2147) Please refer to the linked issue as it is what is happening in your setup. If you would like to continue the discussion please do so in that issue. Discussions should be localized rather than duplicated to make it easier for users who are searching for answers in the future. Another good resource if you have questions is the Discord as there are many users there who can help you out if you are running into issues with your setup.
