### ISSUE TITLE
it always show this bug

### ISSUE THREAD

**Issue by newyorkthink** [AstroNvim/AstroNvim#2147] opened 2023-07-20 01:30 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Debian

### Terminal/GUI

alacritty

### AstroNvim Health

![image](https://github.com/AstroNvim/AstroNvim/assets/87791643/e3d98c5e-890d-4806-bad0-9c874b296041)

### Describe the bug

![image](https://github.com/AstroNvim/AstroNvim/assets/87791643/b4d43271-1165-4d5f-8601-c55dc524e4de)

### Steps to Reproduce

![image](https://github.com/AstroNvim/AstroNvim/assets/87791643/92b67398-d54b-4c2d-a971-289321280f13)

### Expected behavior

![image](https://github.com/AstroNvim/AstroNvim/assets/87791643/c2c92029-e68d-4bbf-9380-568d10485cad)

**Comment by mehalter** [comment] 2023-07-20 01:31
Duplicate of #1699

**Closed by mehalter** 2023-07-20 01:32 UTC
Labels: bug
