### ISSUE TITLE
"AstroMasonLspSetup"..FileType Autocommands for "*":

### ISSUE THREAD

**Issue by MahmoudESSE** [AstroNvim/AstroNvim#2342] opened 2023-10-22 10:06 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Manjaro Linux x86_64 6.1.55-1-MANJARO

### Terminal/GUI

Alacritty

### AstroNvim Health

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.37.7
- Neovim Version: v0.9.4
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

I installed astronvim just as the documentation says and looked at the youtube tutorial but when i entered the nvim config and opened a lua file it resulted in this error

### Steps to Reproduce

1. move nvim files to bak
2. clone the repo
3. then run nvim
4. go to a lua file

### Expected behavior

I expected the file to open and i can use lua lsp as usual with hover and gotos, etc...

### Screenshots

![astro-nvim-bug-1](https://github.com/AstroNvim/AstroNvim/assets/131471373/4ba7fe3c-2777-47ef-8da0-2c80a142e2cf)
![astro-nvim-bug-2](https://github.com/AstroNvim/AstroNvim/assets/131471373/f4debf4c-10d1-4d19-a1ec-471e8413ad7d)

### Additional Context

I tried to check what the issue is and removed everything about neovim from the system and installed it fresh but the problem still exists.

**Comment by mehalter** [comment] 2023-10-22 11:24
Duplicate of #1673

**Closed by mehalter** 2023-10-22 11:24 UTC
Labels: bug
