### ISSUE TITLE
An error occurs when opening yml or .env files

### ISSUE THREAD

**Issue by VolodymyrVorona** [AstroNvim/AstroNvim#2337] opened 2023-10-16 09:44 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

Pop!_OS 22.04 LTS

### Terminal/GUI

kitty

### AstroNvim Health

astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.37.6
- Neovim Version: v0.9.4
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `xdg-open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- WARNING `gdu` is not installed: Used for mappings to pull up disk usage analyzer (Optional)
- WARNING `btm` is not installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

### Describe the bug

An error occurs when opening `.yml` or `.env` files.
I tried editing such files in other _Neovim_ distributions and did not encounter such errors.

### Steps to Reproduce

1. Clone _AstroNvim_ repo
2. Type `nvim` (wait for the plugins to be installed.)
3. Restart _AtroNvim_
4. TSInstall yaml
5. Open `some_file.yml` or `.env` file

### Expected behavior

No errors when editing `.yml` and `.env` files.

### Screenshots

![Screenshot from 2023-10-16 12-26-45](https://github.com/AstroNvim/AstroNvim/assets/53271437/4c59364e-5984-4007-b587-5459b9f4e4ae)

![Screenshot from 2023-10-16 12-39-14](https://github.com/AstroNvim/AstroNvim/assets/53271437/c9caa57d-73f8-4ab8-86c7-a99ad9465871)

**Comment by mehalter** [comment] 2023-10-16 09:52
Duplicate of #1673

**Closed by mehalter** 2023-10-16 09:52 UTC
Labels: bug
