### ISSUE TITLE
Glitch and weirdness when quiting unsaved file with neo-tree opened

### ISSUE THREAD

**Issue by nikolasetiawan** [AstroNvim/AstroNvim#1298] opened 2022-11-13 04:50 UTC
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:PackerSync`
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### AstroNvim version

2.6.5

### Neovim version (>= 0.8)

0.8.0

### Operating system/version

macOS 12.6.1

### Describe the bug

There are weird glitches happening when quiting using :q command while the file is not yet saved and neo-tree is opened.

1. neotree window becomes wider for some reason
<img width="1418" alt="Screen Shot 2022-11-13 at 11 43 35" src="https://user-images.githubusercontent.com/92424267/201506164-4c50c713-580c-479e-ac11-840c37073cbe.png">

2. when trying to execute :q again, neotree window now becomes fullscreen and the file is inside a floating diagnostic window
<img width="1418" alt="Screen Shot 2022-11-13 at 11 43 52" src="https://user-images.githubusercontent.com/92424267/201506141-e5fae624-db75-4345-ab1a-8d076051e2de.png">

Not sure if this can be fixed in AstroNvim alone though.

### Steps to Reproduce

1. Fresh installation AstroNvim.
2. Open a file
3. Open neotree window
4. make changes to the file
5. try to quit using :q or `<leader>`q
6. try to quit again to see the second glitch.
7. That's it

### Expected behavior

error pops and goes away

**Comment by mehalter** [comment] 2022-11-14 14:17
Thanks for reporting this. I have confirmed that this is a bug with `neo-tree` and can be replicated with a minimal neovim config that only loads `neo-tree`. I will be opening an issue there.

**Comment by mehalter** [comment] 2022-11-14 14:25
@nikolasetiawan I have opened an issue upstream. Hopefully this gets resolved. I will follow the progress there as well and make sure it gets fixed. Thanks for reporting this! I am going to go ahead and close this since it needs to be fixed elsewhere.

Relevant issue: https://github.com/nvim-neo-tree/neo-tree.nvim/issues/605

**Closed by mehalter** 2022-11-14 14:25 UTC
Labels: bug, upstream
